host: delhigw.napix.gov.in
info:
  title: CGHS
  version: 1.0.0
  x-ibm-name: cghshcotreatmentsfreetextsearch
  description: This API is for searching CGHS treatments List through city code
    and health care organization ID, health care organization name, treatment
    name and the offset.
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/cghs
paths:
  /cghsHcoTreatmentsFreeTextSearch:
    get:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      tags:
        - Cghshcotreatmentsfreetextsearch
    parameters:
      - in: query
        name: cityId
        type: string
        required: true
      - in: query
        name: hcoId
        type: integer
      - in: query
        name: hcoName
        type: string
      - in: query
        name: treatmentName
        type: string
        required: false
      - in: query
        name: offset
        type: integer
schemes:
  - https
swagger: "2.0"
basePath: /nic/cghs/cghshcotreatmentsfreetextsearch
security:
  - oauth:
      - napix
  - {}
securityDefinitions:
  oauth:
    flow: application
    type: oauth2
    scopes:
      napix: ""
    tokenUrl: //oauth2/token
    x-ibm-oauth-provider: nic-oauth-provider-application-grant-type
  clientIdHeader:
    in: header
    name: X-IBM-Client-Id
    type: apiKey
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://delhigw.napix.gov.in/nic/cghs/cghshcotreatmentsfreetextsearch
      type:
        - production
        - development
  enforced: true
  testable: true
  oauth-servers:
    oauth:
      tokenUrls:
        - https://degateway.napix.gov.in:443/nic/cghs//oauth2/token
      refreshUrls: []
      authorizationUrls: []
  application-authentication:
    certificate: false
