host: delhigw.napix.gov.in
info:
  title: Parivahan
  version: 1.0.0
  x-ibm-name: vahanwebservicespucc
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/parivahan
paths:
  /service/getdataforpucc:
    post:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      parameters:
        - in: formData
          name: merchant_code
          type: string
          required: true
        - in: formData
          name: regnNo
          type: string
          required: true
      tags:
        - Vahanwebservicespucc
schemes:
  - https
swagger: "2.0"
basePath: /nic/parivahan/vahanwebservices
security:
  - client id header: []
    client secret header: []
securityDefinitions:
  client id header:
    in: header
    name: X-Client-Id
    type: apiKey
    x-key-type: client_id
  client secret header:
    in: header
    name: X-Client-Secret
    type: apiKey
    x-key-type: client_secret
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://delhigw.napix.gov.in/nic/parivahan/vahanwebservices
      type:
        - production
        - development
  enforced: true
  testable: true
  application-authentication:
    certificate: false
