host: delhigw.napix.gov.in
info:
  title: eCourts
  version: 1.0.0
  x-ibm-name: hc-caveat-details-api
  description: API provides complete history of the caveat from a High court
    establishment matching the Caveat Code. Input for this API is Establishment
    Code, Caveat Code and other details. Every Caveat has a unique 15 digit
    Caveat Code within the establishment. This unique code can be retrieved by
    accessing Caveat using Caveat Search by party name or Caveat Registration
    Number API.
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/ecourts
paths:
  /:
    get:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      tags:
        - Hc caveat details api
    put:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      tags:
        - Hc caveat details api
    head:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      tags:
        - Hc caveat details api
    post:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      tags:
        - Hc caveat details api
    patch:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      tags:
        - Hc caveat details api
    delete:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      tags:
        - Hc caveat details api
  /caveatdetails:
    get:
      responses:
        "200":
          schema:
            type: string
          description: success
      parameters:
        - in: query
          name: dept_id
          type: string
          required: true
        - in: query
          name: request_str
          type: string
          required: true
        - in: query
          name: request_token
          type: string
          required: true
        - in: query
          name: version
          type: string
          required: true
      tags:
        - Hc caveat details api
schemes:
  - https
swagger: "2.0"
basePath: /nic/ecourts/hc-caveat-details-api
security:
  - Oauth_token:
      - napix
securityDefinitions:
  Oauth_token:
    flow: application
    type: oauth2
    scopes:
      napix: napix
    tokenUrl: //oauth2/token
    x-ibm-oauth-provider: nic-oauth-provider-application-grant-type
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://delhigw.napix.gov.in/nic/ecourts/hc-caveat-details-api
      type:
        - production
        - development
  enforced: true
  testable: true
  oauth-servers:
    Oauth_token:
      tokenUrls:
        - https://degateway.napix.gov.in:443/nic/ecourts//oauth2/token
      refreshUrls: []
      authorizationUrls: []
  application-authentication:
    certificate: false
