host: delhigw.napix.gov.in
info:
  title: CGHS
  version: 1.0.0
  x-ibm-name: verifyotp
  description: This API is for verifing the OTP sent to the CGHS benificiary
    registered mobile number.
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/cghs
paths:
  /verifyOtp:
    post:
      consumes: []
      produces: []
      security:
        - oauth:
            - napix
      responses:
        "200":
          schema:
            type: string
          description: success
      parameters:
        - in: body
          name: verifyOtp
          schema:
            type: object
            title: verifyOtp
          required: true
      tags:
        - Verifyotp
    parameters: []
schemes:
  - https
swagger: "2.0"
basePath: /nic/cghs/verifyotp
security:
  - oauth:
      - napix
  - {}
securityDefinitions:
  oauth:
    flow: application
    type: oauth2
    scopes:
      napix: ""
    tokenUrl: //oauth2/token
    x-ibm-oauth-provider: nic-oauth-provider-application-grant-type
  clientIdHeader:
    in: header
    name: X-IBM-Client-Id
    type: apiKey
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://delhigw.napix.gov.in/nic/cghs/verifyotp
      type:
        - production
        - development
  enforced: true
  testable: true
  oauth-servers:
    oauth:
      tokenUrls:
        - https://degateway.napix.gov.in:443/nic/cghs//oauth2/token
      refreshUrls: []
      authorizationUrls: []
  application-authentication:
    certificate: false
