host: delhigw.napix.gov.in
info:
  title: eCourts
  version: 1.0.0
  x-ibm-name: hc-advocate-bar-reg-api
  description: API provides list of cases from a High court establishment for a
    given Advocate Registration number. Input for this API is Establishment
    Code, Advocate’s Bar Registration Year, Case Registration Year, Status of
    the Case (Pending or Disposed) and other details. The Advocate may be
    petitioner’s advocate or respondent’s advocate or an extra party advocate.
    The search string for advocate bar registration number shall be input in the
    format state characters-bar registration number–registration year.
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/ecourts
paths:
  /:
    get:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      tags:
        - Hc advocate bar reg api
    put:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      tags:
        - Hc advocate bar reg api
    head:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      tags:
        - Hc advocate bar reg api
    post:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      tags:
        - Hc advocate bar reg api
    patch:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      tags:
        - Hc advocate bar reg api
    delete:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      tags:
        - Hc advocate bar reg api
  /advocateBarReg:
    get:
      responses:
        "200":
          schema:
            type: string
          description: success
      parameters:
        - in: query
          name: dept_id
          type: string
          required: true
        - in: query
          name: request_str
          type: string
          required: true
        - in: query
          name: request_token
          type: string
          required: true
        - in: query
          name: version
          type: string
          required: true
      tags:
        - Hc advocate bar reg api
schemes:
  - https
swagger: "2.0"
basePath: /nic/ecourts/hc-advocate-bar-reg-api
security:
  - Ouath_token:
      - napix
  - {}
securityDefinitions:
  Ouath_token:
    flow: application
    type: oauth2
    scopes:
      napix: napix
    tokenUrl: //oauth2/token
    x-ibm-oauth-provider: nic-oauth-provider-application-grant-type
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://delhigw.napix.gov.in/nic/ecourts/hc-advocate-bar-reg-api
      type:
        - production
        - development
  enforced: true
  testable: true
  oauth-servers:
    Ouath_token:
      tokenUrls:
        - https://degateway.napix.gov.in:443/nic/ecourts//oauth2/token
      refreshUrls: []
      authorizationUrls: []
  application-authentication:
    certificate: false
