host: degateway.napix.gov.in:443
info:
  title: Jeevan Pramaan
  version: 1.0.0
  x-ibm-name: mdspenotpgen
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/jeevan-pramaan
paths:
  /mds_penotpgen:
    post:
      summary: PArams
      consumes:
        - application/xml
      responses:
        "200":
          description: Ok
      parameters:
        - in: body
          name: BodyParams
          schema:
            type: string
            title: Schema
        - in: header
          name: AUthorization
          type: string
          format: byte
      tags:
        - Mdspenotpgen
schemes:
  - https
swagger: "2.0"
basePath: /nic/jeevan-pramaan/jeevanpramaan
securityDefinitions:
  clientIdHeader:
    in: header
    name: X-IBM-Client-Id
    type: apiKey
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://degateway.napix.gov.in:443/nic/jeevan-pramaan/jeevanpramaan
      type:
        - production
        - development
      description: ""
  enforced: true
  testable: true
  application-authentication:
    certificate: false
