host: delhigw.napix.gov.in
info:
  title: eCourts
  version: 1.0.0
  x-ibm-name: dc-advocate-name-api
  description: API provides list of cases from a court establishment matching name
    of the Advocate. Input for this API is Establishment Code, Ad vocate’s Name,
    Case Registration Year, Status of the Case (Pending or Disposed) and other
    details. The Advocate’s name may be petitioner’s advocate name or
    respondent’s advocate name or an extra party advocate name. The search
    string for advocate name may consist of full name of the Advocate or even
    few characters (minimum 3) for searching.
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/ecourts
paths:
  /:
    get:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      tags:
        - Dc advocate name api
    put:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      tags:
        - Dc advocate name api
    head:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      tags:
        - Dc advocate name api
    post:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      tags:
        - Dc advocate name api
    patch:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      tags:
        - Dc advocate name api
    delete:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      tags:
        - Dc advocate name api
  /advocateName:
    get:
      responses:
        "200":
          schema:
            type: string
          description: success
      parameters:
        - in: query
          name: dept_id
          type: string
          required: true
        - in: query
          name: request_str
          type: string
          required: true
        - in: query
          name: request_token
          type: string
          required: true
        - in: query
          name: version
          type: string
          required: true
      tags:
        - Dc advocate name api
schemes:
  - https
swagger: "2.0"
basePath: /nic/ecourts/dc-advocate-name-api
security:
  - Oauth_token:
      - napix
  - {}
securityDefinitions:
  Oauth_token:
    flow: application
    type: oauth2
    scopes:
      napix: napix
    tokenUrl: //oauth2/token
    x-ibm-oauth-provider: nic-oauth-provider-application-grant-type
  clientIdHeader:
    in: header
    name: X-IBM-Client-Id
    type: apiKey
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://delhigw.napix.gov.in/nic/ecourts/dc-advocate-name-api
      type:
        - production
        - development
  enforced: true
  testable: true
  oauth-servers:
    Oauth_token:
      tokenUrls:
        - https://degateway.napix.gov.in:443/nic/ecourts//oauth2/token
      refreshUrls: []
      authorizationUrls: []
  application-authentication:
    certificate: false
