host: delhigw.napix.gov.in
info:
  title: Aarogya Sathi Mobile App (RJ)
  version: 1.0.0
  x-ibm-name: subdistrict
  description: This is Spinner API for provide  data Array for app .this is the
    part of AarogyaSathi mobile app functionality .this API needs in multiple
    modules for providing  some defult data  to user .
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/aarogyasathi
paths:
  /subdistrict:
    get:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      tags:
        - Subdistrict
    head:
      responses:
        "200":
          schema:
            type: string
          description: success
      tags:
        - Subdistrict
    post:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      tags:
        - Subdistrict
schemes:
  - https
swagger: "2.0"
basePath: /nic/aarogyasathi/subdistrict
security:
  - Client_ID: []
  - {}
securityDefinitions:
  Client_ID:
    in: header
    name: Client_ID
    type: apiKey
    x-key-type: client_id
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://delhigw.napix.gov.in/nic/aarogyasathi/subdistrict
      type:
        - production
        - development
  enforced: true
  testable: true
  application-authentication:
    certificate: false
