host: bgw.napix.gov.in
info:
  title: API Management for Tripura
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/trapi
  version: 1.0.0
  x-ibm-name: finance_getempdetails
  description: This API of Finance Department, Govt. of Tripura exposes the
    Employee Details(Place of Posting, Post, Designation, Salary etc.) in HRMS
    upon providing the Employee Code.
paths:
  /GetEmpDetails:
    post:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      parameters:
        - in: body
          name: GetEmpDetails
          schema:
            type: object
            properties:
              key:
                type: string
                title: key
              text:
                type: string
                title: text
          required: true
      tags:
        - Finance getempdetails
schemes:
  - https
swagger: "2.0"
basePath: /nic/trapi/getempdetails
security:
  - Client ID: []
    Client Key: []
    Oauth_Token:
      - napix
securityDefinitions:
  Client ID:
    in: header
    name: NIC-Client-ID
    type: apiKey
    x-key-type: client_id
  Client Key:
    in: header
    name: NIC-Client-Key
    type: apiKey
    x-key-type: client_secret
  Oauth_Token:
    flow: application
    type: oauth2
    scopes:
      napix: NAPIX Scope
    tokenUrl: //oauth2/token
    x-ibm-oauth-provider: nic-oauth-provider-application-grant-type
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://bgw.napix.gov.in/nic/trapi/getempdetails
      type:
        - production
        - development
      description: Bhubaneswar External Gateway
  enforced: true
  testable: true
  oauth-servers:
    Oauth_Token:
      tokenUrls:
        - https://begateway.napix.gov.in:443/nic/trapi//oauth2/token
      refreshUrls: []
      authorizationUrls: []
  application-authentication:
    certificate: false
