host: delhigw.napix.gov.in
info:
  title: Reproductive & Child Health
  version: 1.0.0
  x-ibm-name: getaudiofiles_test
  description: Providing list of registered unique identification record related
    to reproductive lifecycle of women and promote, monitor and support the
    reproductive, maternal, new-born and child health (RMNCH) schemes programme
    delivery and reporting
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/rch
paths:
  /:
    get:
      responses:
        "200":
          schema:
            type: string
          description: success
      tags:
        - Getaudiofiles test
schemes:
  - https
swagger: "2.0"
basePath: /nic/rch/getaudiofiles_test
consumes:
  - application/json
produces:
  - application/json
security:
  - oauth:
      - napix
securityDefinitions:
  oauth:
    flow: application
    type: oauth2
    scopes:
      napix: NAPIX Scope
    tokenUrl: //oauth2/token
    x-ibm-oauth-provider: rch-oauth-provider-application-grant-type
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://delhigw.napix.gov.in/nic/rch/getaudiofiles_test
      type:
        - production
        - development
  enforced: true
  testable: true
  oauth-servers:
    oauth:
      tokenUrls:
        - https://degateway.napix.gov.in:443/nic/rch//oauth2/token
      refreshUrls: []
      authorizationUrls: []
  application-authentication: {}
