host: delhigw.napix.gov.in
info:
  title: D/o Empowerment of persons with disabilities(Disability Affairs)
  version: 1.0.0
  x-ibm-name: udid
  description: This API is generally used to fetch the Unique Disability ID (UDID)
    Person with disability (PWD) data.
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/depwd
paths:
  /depwd-udidapi:
    post:
      responses:
        "200":
          description: 200 SUCCESS OK
      parameters: []
      tags:
        - Udid
    parameters:
      - in: formData
        name: udid
        type: string
      - in: formData
        name: enrollmentno
        type: string
      - in: formData
        name: dob
        type: string
schemes:
  - https
swagger: "2.0"
basePath: /nic/depwd/udid-login
security:
  - clientID: []
    ClientSecret: []
securityDefinitions:
  clientID:
    in: header
    name: X-Client-Id
    type: apiKey
    x-key-type: client_id
  ClientSecret:
    in: header
    name: clientsecret
    type: apiKey
    x-key-type: client_secret
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://delhigw.napix.gov.in/nic/depwd/udid-login
      type:
        - production
        - development
  enforced: true
  testable: true
  application-authentication:
    certificate: false
