host: delhigw.napix.gov.in
info:
  title: Parivahan
  version: 1.0.0
  x-ibm-name: sarathiwebservices-non-privacy-details
  description: To get non provacy details from sarathi
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/parivahan
paths:
  /service/getDLNonPrivacyDetails/{dlno}/{dob}/{user}/{password}:
    post:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      parameters:
        - in: path
          name: dlno
          type: string
          required: true
        - in: path
          name: dob
          type: string
          required: true
        - in: path
          name: user
          type: string
          required: true
        - in: path
          name: password
          type: string
          required: true
      tags:
        - Sarathiwebservices non privacy details
schemes:
  - https
swagger: "2.0"
basePath: /nic/parivahan/SarathiService
security:
  - Oauth2Token:
      - scope
securityDefinitions:
  clientID:
    in: header
    name: X-Client-Id
    type: apiKey
    x-key-type: client_id
  Oauth2Token:
    flow: application
    type: oauth2
    scopes:
      napix: napixScope
    tokenUrl: //oauth2/token
    x-ibm-oauth-provider: nic-oauth-provider-application-grant-type
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://delhigw.napix.gov.in/nic/parivahan/SarathiService
      type:
        - production
        - development
  enforced: true
  testable: true
  oauth-servers:
    Oauth2Token:
      tokenUrls:
        - https://degateway.napix.gov.in:443/nic/parivahan//oauth2/token
      refreshUrls: []
      authorizationUrls: []
  application-authentication:
    certificate: false
