host: delhigw.napix.gov.in
info:
  title: Unified Data Hub, Puducherry
  version: 1.0.0
  x-ibm-name: fisheriesbeneficiarydetails
  description: To view Total Number of Fisheries Beneficiary - District Wise -
    Government of Puducherry UT
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/pyudh
paths:
  /fisheriesBeneficiaryDetails:
    get:
      responses:
        "200":
          schema:
            type: string
          description: success
      tags:
        - Fisheriesbeneficiarydetails
schemes:
  - https
swagger: "2.0"
basePath: /nic/pyudh/fisheriesbeneficiarydetails
security:
  - Client-Id: []
    Client Secret: []
securityDefinitions:
  Client-Id:
    in: header
    name: X-NIC-Client-Id
    type: apiKey
    x-key-type: client_id
  Client Secret:
    in: header
    name: X-NIC-Client-Secret
    type: apiKey
    x-key-type: client_secret
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://delhigw.napix.gov.in/nic/pyudh/fisheriesbeneficiarydetails
      type:
        - production
        - development
  enforced: true
  testable: true
  application-authentication: {}
