host: delhigw.napix.gov.in
info:
  title: eCourts
  version: 1.0.0
  x-ibm-name: dc-caveat-name-api
  description: AP I provides li st of Caveats f rom a court establishment matching
    name of the party. Input for this API is Establishment Code, Party Name,
    Search type and other details. Search type parameter provides facility to
    search the name string anywhere ( or starting with (S) wi th the input
    characters The list also includes matched case numbers along with the
    Caveats.
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/ecourts
paths:
  /:
    get:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      tags:
        - Dc caveat name api
    put:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      tags:
        - Dc caveat name api
    head:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      tags:
        - Dc caveat name api
    post:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      tags:
        - Dc caveat name api
    patch:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      tags:
        - Dc caveat name api
    delete:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      tags:
        - Dc caveat name api
  /caveatName:
    get:
      responses:
        "200":
          schema:
            type: string
          description: success
      parameters:
        - in: query
          name: dept_id
          type: string
          required: true
        - in: query
          name: request_str
          type: string
          required: true
        - in: query
          name: request_token
          type: string
          required: true
        - in: query
          name: version
          type: string
          required: true
      tags:
        - Dc caveat name api
schemes:
  - https
swagger: "2.0"
basePath: /nic/ecourts/dc-caveat-name-api
security:
  - Oauth_token:
      - napix
  - {}
securityDefinitions:
  Oauth_token:
    flow: application
    type: oauth2
    scopes:
      napix: napix
    tokenUrl: //oauth2/token
    x-ibm-oauth-provider: nic-oauth-provider-application-grant-type
  clientIdHeader:
    in: header
    name: X-IBM-Client-Id
    type: apiKey
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://delhigw.napix.gov.in/nic/ecourts/dc-caveat-name-api
      type:
        - production
        - development
  enforced: true
  testable: true
  oauth-servers:
    Oauth_token:
      tokenUrls:
        - https://degateway.napix.gov.in:443/nic/ecourts//oauth2/token
      refreshUrls: []
      authorizationUrls: []
  application-authentication:
    certificate: false
