host: delhigw.napix.gov.in
info:
  title: Parivahan
  version: 1.0.0
  x-ibm-name: vahan-ws-report-nesd-data
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/parivahan
paths:
  /service/getNesdData:
    get:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      parameters:
        - in: query
          name: transdate
          type: string
          required: true
        - in: query
          name: user
          type: string
          required: true
        - in: query
          name: password
          type: string
          required: true
      tags:
        - Vahan ws report nesd data
schemes:
  - https
swagger: "2.0"
basePath: /nic/parivahan/VahanWSReport
security:
  - Oauth2Token:
      - napix
securityDefinitions:
  Oauth2Token:
    flow: application
    type: oauth2
    scopes:
      napix: napixScope
    tokenUrl: //oauth2/token
    x-ibm-oauth-provider: nic-oauth-provider-application-grant-type
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://delhigw.napix.gov.in/nic/parivahan/VahanWSReport
      type:
        - production
        - development
  enforced: true
  testable: true
  oauth-servers:
    Oauth2Token:
      tokenUrls:
        - https://degateway.napix.gov.in:443/nic/parivahan//oauth2/token
      refreshUrls: []
      authorizationUrls: []
  application-authentication:
    certificate: false
