host: delhigw.napix.gov.in
info:
  title: Unified Data Hub, Puducherry
  version: 1.0.0
  x-ibm-name: dist-wise-ration-card-details
  description: To view Total Number of Ration Card - Card Type wise of a
    particular District - Government of Puducherry UT
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/pyudh
paths:
  /RCD/{districtCode}:
    get:
      consumes: []
      responses:
        "200":
          schema:
            type: string
          description: success
      parameters: []
      tags:
        - Dist wise ration card details
    parameters:
      - in: path
        name: districtCode
        type: integer
        required: true
schemes:
  - https
swagger: "2.0"
basePath: /nic/pyudh/dist-wise-ration-card-details
security:
  - Client ID: []
    Client Secret: []
securityDefinitions:
  Client ID:
    in: header
    name: X-NIC-Client-Id
    type: apiKey
    x-key-type: client_id
  Client Secret:
    in: header
    name: X-NIC-Client-Secret
    type: apiKey
    x-key-type: client_secret
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://delhigw.napix.gov.in/nic/pyudh/dist-wise-ration-card-details
      type:
        - production
        - development
  enforced: true
  testable: true
  application-authentication: {}
