info:
  title: LGD
  version: 1.0.0
  x-ibm-name: subdistrictsbyduration
  description: >
    To fetch the Local Government Directory (LGD) Codes and additional
    information of all **sub-districts** of India updated between given dates
    using updatedTo and updatedFrom dates as input parameters.
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/lgd
paths:
  /subdistricts/v1/updatedFrom/{updatedFrom}/updatedTo/{updatedTo}:
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: success
      parameters:
        - in: path
          name: updatedFrom
          schema:
            type: string
          required: true
        - in: path
          name: updatedTo
          schema:
            type: string
          required: true
      tags:
        - Subdistrictsbyduration
openapi: 3.0.0
servers:
  - url: https://delhigw.napix.gov.in/nic/lgd
    description: LGD Vanity Endpoint
security:
  - clientID: []
    clientSecret: []
components:
  schemas:
    date:
      type: string
  securitySchemes:
    clientID:
      in: header
      name: X-IBM-Client-Id
      type: apiKey
      x-key-type: client_id
    clientSecret:
      in: header
      name: X-IBM-Client-Secret
      type: apiKey
      x-key-type: client_secret
x-ibm-endpoints:
  - url: https://delhigw.napix.gov.in/nic/lgd
    type:
      - production
      - development
    description: LGD Vanity Endpoint
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  enforced: true
  testable: true
