host: bgw.napix.gov.in
info:
  title: API Management for Tripura
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/trapi
  version: 1.0.0
  x-ibm-name: finance_getdeptcode
  description: This API of Finance Department, Govt. of Tripura list out the
    Department Names & Department Codes onboarded in HRMS.
paths:
  /getdeptcode:
    post:
      responses:
        "200":
          schema:
            type: string
          description: success
      parameters:
        - in: body
          name: getdeptcode
          schema:
            type: object
            properties:
              key:
                type: string
                title: key
              text:
                type: string
                title: text
          required: true
      tags:
        - Finance getdeptcode
schemes:
  - https
swagger: "2.0"
basePath: /nic/trapi/getdeptcode
security:
  - Oauth:
      - napix
    Client ID: []
    Client Key: []
securityDefinitions:
  Oauth:
    flow: application
    type: oauth2
    scopes:
      napix: NAPIX Scope
    tokenUrl: //oauth2/token
    x-ibm-oauth-provider: nic-oauth-provider-application-grant-type
  Client ID:
    in: header
    name: NIC-Client-ID
    type: apiKey
    x-key-type: client_id
  Client Key:
    in: header
    name: NIC-Client-Key
    type: apiKey
    x-key-type: client_secret
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://bgw.napix.gov.in/nic/trapi/getdeptcode
      type:
        - production
        - development
      description: Bhubaneswar External Gateway
  enforced: true
  testable: true
  oauth-servers:
    Oauth:
      tokenUrls:
        - https://begateway.napix.gov.in:443/nic/trapi//oauth2/token
      refreshUrls: []
      authorizationUrls: []
  application-authentication:
    certificate: false
