host: delhigw.napix.gov.in
info:
  title: Parivahan
  version: 1.0.0
  x-ibm-name: sarathi-api-s5rule-service-documents
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/parivahan
paths:
  /s5Rule/service/documents/{stateCd}/{transCd}/{applNo}/{applCatg}:
    get:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      parameters:
        - in: path
          name: stateCd
          type: string
          required: true
        - in: path
          name: transCd
          type: string
          required: true
        - in: path
          name: applNo
          type: string
          required: true
        - in: path
          name: applCatg
          type: string
          required: true
      tags:
        - Sarathi api s5rule service documents
schemes:
  - https
swagger: "2.0"
basePath: /nic/parivahan/sarathiapi
security:
  - Oauth2Token:
      - napix
securityDefinitions:
  clientID:
    in: header
    name: X-Client-Id
    type: apiKey
    x-key-type: client_id
  Oauth2Token:
    flow: application
    type: oauth2
    scopes:
      napix: napixScope
    tokenUrl: //oauth2/token
    x-ibm-oauth-provider: nic-oauth-provider-application-grant-type
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://delhigw.napix.gov.in/nic/parivahan/sarathiapi
      type:
        - production
        - development
  enforced: true
  testable: true
  oauth-servers:
    Oauth2Token:
      tokenUrls:
        - https://degateway.napix.gov.in:443/nic/parivahan//oauth2/token
      refreshUrls: []
      authorizationUrls: []
  application-authentication:
    certificate: false
