info:
  title: CoeAILabKol
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/wb/coeailabkol
  version: 1.0.0
  x-ibm-name: crowd-count
  description: This is an AI enabled API which takes image as an input and returns
    number of people in the image.
paths:
  /crowd-count:
    post:
      summary: Create Upload File
      responses:
        "200":
          content:
            application/json:
              schema: {}
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                type: object
                title: HTTPValidationError
                properties:
                  detail:
                    type: array
                    items:
                      type: object
                      title: ValidationError
                      required:
                        - loc
                        - msg
                        - type
                      properties:
                        loc:
                          type: array
                          items:
                            anyOf:
                              - type: string
                              - type: integer
                          title: Location
                        msg:
                          type: string
                          title: Message
                        type:
                          type: string
                          title: Error Type
                    title: Detail
          description: Validation Error
      operationId: create_upload_file_crowd_count_post
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              title: Body_create_upload_file_crowd_count_post
              required:
                - file
              properties:
                file:
                  type: string
                  title: File
                  format: binary
        required: true
      tags:
        - Crowd count
openapi: 3.0.0
servers:
  - url: https://wb-gateway.napix.gov.in/wb/coeailabkol
    description: ""
security:
  - Client-ID: []
    Client-Secret: []
components:
  schemas:
    ValidationError:
      type: object
      title: ValidationError
      required:
        - loc
        - msg
        - type
      properties:
        loc:
          type: array
          items:
            anyOf:
              - type: string
              - type: integer
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
    HTTPValidationError:
      type: object
      title: HTTPValidationError
      properties:
        detail:
          type: array
          items:
            type: object
            title: ValidationError
            required:
              - loc
              - msg
              - type
            properties:
              loc:
                type: array
                items:
                  anyOf:
                    - type: string
                    - type: integer
                title: Location
              msg:
                type: string
                title: Message
              type:
                type: string
                title: Error Type
          title: Detail
    Body_create_upload_file_crowd_count_post:
      type: object
      title: Body_create_upload_file_crowd_count_post
      required:
        - file
      properties:
        file:
          type: string
          title: File
          format: binary
  securitySchemes:
    Client-ID:
      in: header
      name: client-id
      type: apiKey
      x-key-type: client_id
      description: description of client id
    Client-Secret:
      in: header
      name: client-secret
      type: apiKey
      x-key-type: client_secret
x-ibm-endpoints:
  - url: https://wb-gateway.napix.gov.in/wb/coeailabkol
    description: ""
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  enforced: true
  testable: true
