host: delhigw.napix.gov.in
info:
  title: CGHS
  version: 1.0.0
  x-ibm-name: getdoctor
  description: This API displays Doctor name, speciality of Doctor - City and
    Dispensary wise.
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/cghs
paths:
  /getdoctor:
    post:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      parameters:
        - in: body
          name: doctorData
          schema:
            type: object
            title: doctorData
            required:
              - benId
              - initialToken
              - latestToken
              - cityCode
              - specialityCode
              - dispensaryCode
            properties:
              benId:
                type: string
              cityCode:
                type: string
              latestToken:
                type: string
              initialToken:
                type: string
              dispensaryCode:
                type: string
              specialityCode:
                type: string
          required: true
      tags:
        - Getdoctor
schemes:
  - https
swagger: "2.0"
basePath: /nic/cghs/getdoctor
security:
  - oauth:
      - napix
  - {}
securityDefinitions:
  oauth:
    flow: application
    type: oauth2
    scopes:
      napix: ""
    tokenUrl: //oauth2/token
    x-ibm-oauth-provider: nic-oauth-provider-application-grant-type
  clientIdHeader:
    in: header
    name: X-IBM-Client-Id
    type: apiKey
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://delhigw.napix.gov.in/nic/cghs/getdoctor
      type:
        - production
        - development
  enforced: true
  testable: true
  oauth-servers:
    oauth:
      tokenUrls:
        - https://degateway.napix.gov.in:443/nic/cghs//oauth2/token
      refreshUrls: []
      authorizationUrls: []
  application-authentication:
    certificate: false
