host: delhigw.napix.gov.in
info:
  title: CGHS
  version: 1.0.0
  x-ibm-name: labreportcategory
  description: This api provides lab report categories like **Serology**, **Blood
    Testing**, and **Clinical Chemistry**
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/cghs
paths:
  /labReportCategory:
    get:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      tags:
        - Labreportcategory
    post:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      parameters:
        - in: body
          name: SubCategory
          schema:
            type: object
            title: category
      tags:
        - Labreportcategory
schemes:
  - https
swagger: "2.0"
basePath: /nic/cghs/labreportcategory
security:
  - oauth:
      - napix
  - {}
securityDefinitions:
  oauth:
    flow: application
    type: oauth2
    scopes:
      napix: ""
    tokenUrl: //oauth2/token
    x-ibm-oauth-provider: nic-oauth-provider-application-grant-type
  clientIdHeader:
    in: header
    name: X-IBM-Client-Id
    type: apiKey
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://delhigw.napix.gov.in/nic/cghs/labreportcategory
      type:
        - production
        - development
  enforced: true
  testable: true
  oauth-servers:
    oauth:
      tokenUrls:
        - https://degateway.napix.gov.in:443/nic/cghs//oauth2/token
      refreshUrls: []
      authorizationUrls: []
  application-authentication:
    certificate: false
