host: delhigw.napix.gov.in
info:
  title: Reproductive & Child Health
  version: 1.0.0
  x-ibm-name: abhagetpngcard
  description: Providing list of health facility registered record related to
    reproductive lifecycle of women delivery of immunization services to
    children born and child health (RMNCH).
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/rch
paths:
  /:
    get:
      schemes:
        - https
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          schema:
            type: string
          description: success
      parameters:
        - in: header
          name: X-TOKEN
          type: string
          required: true
      tags:
        - Abhagetpngcard
schemes:
  - https
swagger: "2.0"
basePath: /nic/rch/abhagetpngcard
consumes:
  - application/json
produces:
  - application/json
security:
  - oauth:
      - napix
securityDefinitions:
  oauth:
    flow: application
    type: oauth2
    scopes:
      napix: NAPIX Scope
    tokenUrl: //oauth2/token
    x-ibm-oauth-provider: rch-oauth-provider-application-grant-type
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://delhigw.napix.gov.in/nic/rch/abhagetpngcard
      type:
        - production
        - development
  enforced: true
  testable: true
  oauth-servers:
    oauth:
      tokenUrls:
        - https://degateway.napix.gov.in:443/nic/rch//oauth2/token
      refreshUrls: []
      authorizationUrls: []
  application-authentication: {}
