host: delhigw.napix.gov.in
info:
  title: Unified Data Hub, Puducherry
  version: 1.0.0
  x-ibm-name: payment-status
  description: To view the DBT Payment Status of a Public Distribution System
    Beneficiary of Government of Puducherry
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/pyudh
paths:
  /dbtps:
    post:
      responses:
        "200":
          schema:
            type: string
          description: success
      parameters:
        - in: query
          name: district
          type: string
          required: true
        - in: query
          name: rcno
          type: string
          required: true
      tags:
        - Payment status
    parameters: []
schemes:
  - https
swagger: "2.0"
basePath: /nic/pyudh/payment-status
security:
  - Client ID: []
    Client Secret: []
securityDefinitions:
  Client ID:
    in: header
    name: X-NIC-Client-Id
    type: apiKey
    x-key-type: client_id
  Client Secret:
    in: header
    name: X-NIC-Client-Secret
    type: apiKey
    x-key-type: client_secret
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://delhigw.napix.gov.in/nic/pyudh/payment-status
      type:
        - production
        - development
  enforced: true
  testable: true
  application-authentication: {}
