host: delhigw.napix.gov.in
info:
  title: CGHS
  version: 1.0.0
  x-ibm-name: newshighlight
  description: This API Fetch CGHS beneficiaries related News and Updates and
    Search News Updates through the Link Name, Link Name like name of the topic.
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/cghs
paths:
  /newsHighlight:
    post:
      responses:
        "200":
          schema:
            type: string
          description: success
      parameters:
        - in: body
          name: newsList
          schema:
            type: object
            title: cghsnews
            properties:
              linkName:
                type: object
                title: linkName
                properties: {}
          description: Can List of CGHS News and Search News also  through linkName
      tags:
        - Newshighlight
    parameters: []
schemes:
  - https
swagger: "2.0"
basePath: /nic/cghs/newshighlight
security:
  - oauth:
      - napix
securityDefinitions:
  oauth:
    flow: application
    type: oauth2
    scopes:
      napix: ""
    tokenUrl: //oauth2/token
    x-ibm-oauth-provider: nic-oauth-provider-application-grant-type
  clientIdHeader:
    in: header
    name: X-IBM-Client-Id
    type: apiKey
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://delhigw.napix.gov.in/nic/cghs/newshighlight
      type:
        - production
        - development
  enforced: true
  testable: true
  oauth-servers:
    oauth:
      tokenUrls:
        - https://degateway.napix.gov.in:443/nic/cghs//oauth2/token
      refreshUrls: []
      authorizationUrls: []
  application-authentication:
    certificate: false
