host: wb-gateway.napix.gov.in
info:
  title: WB Land Records
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/wb/wblandrecords
  version: 1.0.0
  x-ibm-name: listmouzawithname
  description: This API provide the mouza name based on mouza code, district code,
    block code . Its required a password to authenticate the API
paths:
  /listmouzawithname/{dcode}/{bcode}/{moucode}/{requestFrom}/{password}:
    get:
      responses:
        "200":
          schema:
            type: string
          description: success
      parameters: []
      tags:
        - Listmouzawithname
    parameters:
      - in: path
        name: dcode
        type: string
        required: true
      - in: path
        name: bcode
        type: string
        required: true
      - in: path
        name: moucode
        type: string
        required: true
      - in: path
        name: requestFrom
        type: string
        required: true
      - in: path
        name: password
        type: string
        required: true
schemes:
  - https
swagger: "2.0"
basePath: /wb/wblandrecords
security:
  - clientID: []
    clientSecret: []
parameters: {}
securityDefinitions:
  clientID:
    in: header
    name: client_id
    type: apiKey
    x-key-type: client_id
  clientSecret:
    in: header
    name: client_secret
    type: apiKey
    x-key-type: client_secret
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://wb-gateway.napix.gov.in/wb/wblandrecords
      type:
        - production
        - development
      description: ""
  enforced: true
  testable: true
  application-authentication: {}
