info:
  title: LGD
  version: 1.0.0
  x-ibm-name: operationsbystatebyduration
  description: To fetch all the records of Operations done by a state between
    given dates in Local Government Directory (LGD) portal using LGD state code,
    updatedTo and updatedFrom dates as input parameters.
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/lgd
paths:
  /state/{stateCode}/operations/v1/updatedFrom/{updatedFrom}/updatedTo/{updatedTo}/page/{page}:
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: success
      parameters:
        - in: path
          name: stateCode
          schema:
            type: integer
          required: true
        - in: path
          name: updatedFrom
          schema:
            type: string
          required: true
        - in: path
          name: updatedTo
          schema:
            type: string
          required: true
        - in: path
          name: page
          schema:
            type: integer
          required: true
      tags:
        - Operationsbystatebyduration
openapi: 3.0.0
servers:
  - url: https://delhigw.napix.gov.in/nic/lgd
    description: LGD Vanity Endpoint
security:
  - clientID: []
    clientSecret: []
components:
  schemas:
    code:
      type: integer
    date:
      type: string
    page:
      type: integer
  securitySchemes:
    clientID:
      in: header
      name: X-IBM-Client-Id
      type: apiKey
      x-key-type: client_id
    clientSecret:
      in: header
      name: X-IBM-Client-Secret
      type: apiKey
      x-key-type: client_secret
x-ibm-endpoints:
  - url: https://delhigw.napix.gov.in/nic/lgd
    type:
      - production
      - development
    description: LGD Vanity Endpoint
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  enforced: true
  testable: true
