host: delhigw.napix.gov.in
info:
  title: CGHS
  version: 1.0.0
  x-ibm-name: getcaldata
  description: This API is for finding the Doctor name, their specialty, city and
    wellness centre and concerned available slots.
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/cghs
paths:
  /getcaldata:
    post:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      parameters:
        - in: body
          name: calData
          schema:
            type: object
            title: calData
            properties:
              benId:
                type: string
              doctor:
                type: string
              cityCode:
                type: string
              latestToken:
                type: string
              specialtyId:
                type: string
              initialToken:
                type: string
              dispensaryCode:
                type: string
          required: true
      tags:
        - Getcaldata
schemes:
  - https
swagger: "2.0"
basePath: /nic/cghs/getcaldata
security:
  - oauth:
      - napix
securityDefinitions:
  oauth:
    flow: application
    type: oauth2
    scopes:
      napix: ""
    tokenUrl: //oauth2/token
    x-ibm-oauth-provider: nic-oauth-provider-application-grant-type
  clientIdHeader:
    in: header
    name: X-IBM-Client-Id
    type: apiKey
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://delhigw.napix.gov.in/nic/cghs/getcaldata
      type:
        - production
        - development
  enforced: true
  testable: true
  oauth-servers:
    oauth:
      tokenUrls:
        - https://degateway.napix.gov.in:443/nic/cghs//oauth2/token
      refreshUrls: []
      authorizationUrls: []
  application-authentication:
    certificate: false
