host: delhigw.napix.gov.in
info:
  title: CGHS
  version: 1.0.0
  x-ibm-name: cghscityhcotreatment
  description: This API gives treatment ID and treatment name provided by the HCO
    (Health Care Organisation) ID and takes HCO ID as input.
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/cghs
paths:
  /cghsCityHcoTreatment:
    get:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      parameters:
        - in: query
          name: hcoId
          type: integer
          required: true
      tags:
        - Cghscityhcotreatment
    parameters: []
schemes:
  - https
swagger: "2.0"
basePath: /nic/cghs/cghscityhcotreatment
security:
  - oauth:
      - napix
  - {}
securityDefinitions:
  oauth:
    flow: application
    type: oauth2
    scopes:
      napix: ""
    tokenUrl: //oauth2/token
    x-ibm-oauth-provider: nic-oauth-provider-application-grant-type
  clientIdHeader:
    in: header
    name: X-IBM-Client-Id
    type: apiKey
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://delhigw.napix.gov.in/nic/cghs/cghscityhcotreatment
      type:
        - production
        - development
  enforced: true
  testable: true
  oauth-servers:
    oauth:
      tokenUrls:
        - https://degateway.napix.gov.in:443/nic/cghs//oauth2/token
      refreshUrls: []
      authorizationUrls: []
  application-authentication:
    certificate: false
