host: delhigw.napix.gov.in
info:
  title: Reproductive & Child Health
  version: 1.0.0
  x-ibm-name: state_motherdelivery_test
  description: Capturing of the individual beneficiary throughout the reproductive
    lifecycle of women  support the reproductive, maternal, new-born and child
    health (RMNCH) schemes programme delivery and reporting.
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/rch
paths:
  /:
    post:
      schemes:
        - https
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          schema:
            type: string
          description: success
      parameters:
        - in: body
          name: body
          schema:
            type: object
            title: body
            properties:
              deel:
                type: string
              keel:
                type: string
          required: true
      tags:
        - State motherdelivery test
schemes:
  - https
swagger: "2.0"
basePath: /nic/rch/state_motherdelivery_test
consumes:
  - application/json
produces:
  - application/json
security:
  - oauth:
      - napix
securityDefinitions:
  oauth:
    flow: application
    type: oauth2
    scopes:
      napix: NAPIX Scope
    tokenUrl: //oauth2/token
    x-ibm-oauth-provider: rch-oauth-provider-application-grant-type
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://delhigw.napix.gov.in/nic/rch/state_motherdelivery_test
      type:
        - production
        - development
  enforced: true
  testable: true
  oauth-servers:
    oauth:
      tokenUrls:
        - https://degateway.napix.gov.in:443/nic/rch//oauth2/token
      refreshUrls: []
      authorizationUrls: []
  application-authentication: {}
