host: delhigw.napix.gov.in
info:
  title: Dedupe
  version: "1.0"
  x-ibm-name: uploaddedupestatusreport
  description: Upload Dedupe StatusReport
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/dedupe
tags:
  - name: transaction
    description: transaction
paths:
  /api/transaction/UploadDedupeStatusReport:
    post:
      tags:
        - Uploaddedupestatusreport
      summary: UploadDedupeStatusReport
      consumes:
        - application/json
      produces:
        - "*/*"
      responses:
        "200":
          schema:
            type: object
            additionalProperties:
              type: string
          description: OK
        "201":
          description: Created
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
      parameters:
        - in: body
          name: uploadDedupereport
          schema:
            type: object
            title: UploadDedupereport
            properties:
              uploadDedupeStatusReport:
                type: object
                title: UploadDedupeStatusReport
                properties:
                  login_id:
                    type: integer
                    format: int32
                  report_id:
                    type: integer
                    format: int64
                  project_id:
                    type: integer
                    format: int32
                  total_records:
                    type: integer
                    format: int32
                  application_id:
                    type: integer
                    format: int64
                  matched_records:
                    type: integer
                    format: int32
                  insufficient_records:
                    type: integer
                    format: int32
              uploadDedupeStatusReportDetails:
                type: array
                items:
                  type: object
                  title: UploadDedupeStatusReportDetail
                  properties:
                    remarks:
                      type: string
                    end_time:
                      type: string
                      format: date-time
                    thread_id:
                      type: integer
                      format: int32
                    start_time:
                      type: string
                      format: date-time
                    time_taken:
                      type: string
                    estimate_time:
                      type: string
                    total_records:
                      type: integer
                      format: int64
                    activity_type_id:
                      type: integer
                      format: int32
                    processed_records:
                      type: integer
                      format: int64
                    activity_status_id:
                      type: integer
                      format: int32
          required: true
          description: uploadDedupereport
      operationId: UploadDedupeStatusReportUsingPOST
schemes:
  - https
swagger: "2.0"
basePath: /nic/dedupe
security:
  - Oauth:
      - napix
definitions:
  UploadDedupereport:
    type: object
    title: UploadDedupereport
    properties:
      uploadDedupeStatusReport:
        type: object
        title: UploadDedupeStatusReport
        properties:
          login_id:
            type: integer
            format: int32
          report_id:
            type: integer
            format: int64
          project_id:
            type: integer
            format: int32
          total_records:
            type: integer
            format: int32
          application_id:
            type: integer
            format: int64
          matched_records:
            type: integer
            format: int32
          insufficient_records:
            type: integer
            format: int32
      uploadDedupeStatusReportDetails:
        type: array
        items:
          type: object
          title: UploadDedupeStatusReportDetail
          properties:
            remarks:
              type: string
            end_time:
              type: string
              format: date-time
            thread_id:
              type: integer
              format: int32
            start_time:
              type: string
              format: date-time
            time_taken:
              type: string
            estimate_time:
              type: string
            total_records:
              type: integer
              format: int64
            activity_type_id:
              type: integer
              format: int32
            processed_records:
              type: integer
              format: int64
            activity_status_id:
              type: integer
              format: int32
  UploadDedupeStatusReport:
    type: object
    title: UploadDedupeStatusReport
    properties:
      login_id:
        type: integer
        format: int32
      report_id:
        type: integer
        format: int64
      project_id:
        type: integer
        format: int32
      total_records:
        type: integer
        format: int32
      application_id:
        type: integer
        format: int64
      matched_records:
        type: integer
        format: int32
      insufficient_records:
        type: integer
        format: int32
  UploadDedupeStatusReportDetail:
    type: object
    title: UploadDedupeStatusReportDetail
    properties:
      remarks:
        type: string
      end_time:
        type: string
        format: date-time
      thread_id:
        type: integer
        format: int32
      start_time:
        type: string
        format: date-time
      time_taken:
        type: string
      estimate_time:
        type: string
      total_records:
        type: integer
        format: int64
      activity_type_id:
        type: integer
        format: int32
      processed_records:
        type: integer
        format: int64
      activity_status_id:
        type: integer
        format: int32
securityDefinitions:
  Oauth:
    flow: application
    type: oauth2
    scopes:
      napix: ""
    tokenUrl: //oauth2/token
    x-ibm-oauth-provider: nic-oauth-provider-application-grant-type
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://delhigw.napix.gov.in/nic/dedupe
      type:
        - production
        - development
  enforced: true
  testable: true
  oauth-servers:
    Oauth:
      tokenUrls:
        - https://degateway.napix.gov.in:443/nic/dedupe//oauth2/token
      refreshUrls: []
      authorizationUrls: []
  application-authentication:
    certificate: false
