host: wb-gateway.napix.gov.in
info:
  title: Food & Supplies Department
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/wb/food-supplies
  version: 1.0.0
  x-ibm-name: ekyc-info-api-by-aadhar
  description: API for fetching eKYC information by Aadhar number. This API is JWT
    based. It can cater single as well as bulk data rendering.
paths:
  /:
    post:
      consumes:
        - application/json
      responses:
        "200":
          schema:
            type: string
          description: success
      parameters:
        - in: body
          name: body
          schema:
            type: object
            title: body
            properties:
              param:
                type: array
                properties: {}
              clientId:
                type: string
          required: true
        - in: header
          name: Authorization
          type: string
          required: true
      tags:
        - Ekyc info api by aadhar
    parameters: []
schemes:
  - https
swagger: "2.0"
basePath: /wb/food-supplies/ekyc-info-api-by-aadhar
security:
  - clientID: []
    clientSecret: []
parameters: {}
securityDefinitions:
  clientID:
    in: header
    name: client-Id
    type: apiKey
    x-key-type: client_id
  clientSecret:
    in: header
    name: client-Secret
    type: apiKey
    x-key-type: client_secret
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://wb-gateway.napix.gov.in/wb/food-supplies/ekyc-info-api-by-aadhar
      type:
        - production
        - development
      description: ""
  enforced: true
  testable: true
  application-authentication: {}
