host: bgw.napix.gov.in
info:
  title: API Management for Tripura
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/trapi
  version: 1.0.0
  x-ibm-name: urban_dev_gettradelicdetails
  description: This API is used to get the details of a trade licence with trade
    licence number.
paths:
  /gettradelicdetails:
    post:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      parameters:
        - in: body
          name: trdlicno
          schema:
            type: object
            properties:
              trdlicno:
                type: string
                title: trdlicno
          required: true
      tags:
        - Urban dev gettradelicdetails
schemes:
  - https
swagger: "2.0"
basePath: /nic/trapi/gettradelicdetails
security:
  - Oauth:
      - napix
securityDefinitions:
  Oauth:
    flow: application
    type: oauth2
    scopes:
      napix: NAPIX Scope
    tokenUrl: //oauth2/token
    x-ibm-oauth-provider: nic-oauth-provider-application-grant-type
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://bgw.napix.gov.in/nic/trapi/gettradelicdetails
      type:
        - production
        - development
      description: Bhubaneswar External Gateway
  enforced: true
  testable: true
  oauth-servers:
    Oauth:
      tokenUrls:
        - https://begateway.napix.gov.in:443/nic/trapi//oauth2/token
      refreshUrls: []
      authorizationUrls: []
  application-authentication:
    certificate: false
