info:
  title: Department Of Higher Education and School Education Department, Govt of
    West Bengal
  version: 1.0.0
  x-ibm-name: wbscc-loan-sanctioned-edit-details-national
  description: WBSCC Loan Sanctioned Applicant List Edit Details (National)
    Service gives details of all National Applications Loan Sanction List under
    WBSCC whose sanction details have been undated by Bank after sanctioning.
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/wb/education
paths:
  /loan_sanctioned_edit_details_national:
    post:
      security: []
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: success
        "401":
          description: NOT AUTHORIZED
        "404":
          description: DATA NOT FOUND
        "422":
          description: Valid Date Range Missing
      parameters:
        - in: query
          name: fromDate
          schema:
            type: string
            title: fromDate
            description: From Date
          example: fromDate=15-11-2022
          required: true
          description: Form Date
        - in: query
          name: toDate
          schema:
            type: string
            title: toDate
            description: To Date
          example: toDate=10-12-2022
          required: true
          description: To date
      requestBody:
        content:
          multipart/form-data: {}
      tags:
        - Wbscc loan sanctioned edit details national
openapi: 3.0.0
servers:
  - url: https://wbgw.napix.gov.in/wb/education/wbscc
security:
  - clientID: []
    clientSecret: []
components:
  securitySchemes:
    clientID:
      in: header
      name: X-NIC-Client-Id
      type: apiKey
      x-key-type: client_id
    clientSecret:
      in: header
      name: X-NIC-Client-Secret
      type: apiKey
      x-key-type: client_secret
x-ibm-endpoints:
  - url: https://wbgw.napix.gov.in/wb/education/wbscc
    type:
      - production
      - development
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  enforced: true
  testable: true
