host: delhigw.napix.gov.in
info:
  title: CGHS
  version: 1.0.0
  x-ibm-name: empanelledhostreatments
  description: An API for getting the treatment names provided by CGHS hospital.
    It takes hospital ID as an input parameter.
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/cghs
paths:
  /empanelledHosTreatments:
    get:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      tags:
        - Empanelledhostreatments
    parameters:
      - in: query
        name: hospCode
        type: string
        required: true
schemes:
  - https
swagger: "2.0"
basePath: /nic/cghs/empanelledhostreatments
security:
  - oauth:
      - napix
  - {}
securityDefinitions:
  oauth:
    flow: application
    type: oauth2
    scopes:
      napix: ""
    tokenUrl: //oauth2/token
    x-ibm-oauth-provider: nic-oauth-provider-application-grant-type
  clientIdHeader:
    in: header
    name: X-IBM-Client-Id
    type: apiKey
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://delhigw.napix.gov.in/nic/cghs/empanelledhostreatments
      type:
        - production
        - development
  enforced: true
  testable: true
  oauth-servers:
    oauth:
      tokenUrls:
        - https://degateway.napix.gov.in:443/nic/cghs//oauth2/token
      refreshUrls: []
      authorizationUrls: []
  application-authentication:
    certificate: false
