host: delhigw.napix.gov.in
info:
  title: CGHS
  version: 1.0.0
  x-ibm-name: getdispensarydetails
  description: This API is for dispensary details like Name, Code, City Code along
    with dispensary image, longitude, latitude.
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/cghs
paths:
  /getdispensarydetails:
    post:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      parameters:
        - in: body
          name: getdispensarydetailsPara
          schema:
            type: object
            title: getdispensarydetailsSchema
            properties:
              benId:
                type: string
              cityCode:
                type: string
              dispCode:
                type: string
              latestToken:
                type: string
              initialToken:
                type: string
              fetchDispImageFlag:
                type: string
          required: true
      tags:
        - Getdispensarydetails
schemes:
  - https
swagger: "2.0"
basePath: /nic/cghs/getdispensarydetails
security:
  - oauth:
      - napix
  - {}
securityDefinitions:
  oauth:
    flow: application
    type: oauth2
    scopes:
      napix: ""
    tokenUrl: //oauth2/token
    x-ibm-oauth-provider: nic-oauth-provider-application-grant-type
  clientIdHeader:
    in: header
    name: X-IBM-Client-Id
    type: apiKey
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://delhigw.napix.gov.in/nic/cghs/getdispensarydetails
      type:
        - production
        - development
  enforced: true
  testable: true
  oauth-servers:
    oauth:
      tokenUrls:
        - https://degateway.napix.gov.in:443/nic/cghs//oauth2/token
      refreshUrls: []
      authorizationUrls: []
  application-authentication:
    certificate: false
