host: delhigw.napix.gov.in
info:
  title: CGHS
  version: 1.0.0
  x-ibm-name: getcity
  description: Get city related data while booking appointment with or without
    initial, latest Token
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/cghs
tags:
  - name: Get City with and without initial and latest Token
paths:
  /getCity:
    post:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      parameters:
        - in: body
          name: getCityPara
          schema:
            type: object
            title: getCitySchema
            properties:
              benId:
                type: string
              rosterFlag:
                type: integer
              latestToken:
                type: string
              initialToken:
                type: string
          required: true
      tags:
        - Getcity
schemes:
  - https
swagger: "2.0"
basePath: /nic/cghs/getcity
security:
  - oauth:
      - napix
securityDefinitions:
  oauth:
    flow: application
    type: oauth2
    scopes:
      napix: ""
    tokenUrl: //oauth2/token
    x-ibm-oauth-provider: nic-oauth-provider-application-grant-type
  clientIdHeader:
    in: header
    name: X-IBM-Client-Id
    type: apiKey
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://delhigw.napix.gov.in/nic/cghs/getcity
      type:
        - production
        - development
  enforced: true
  testable: true
  oauth-servers:
    oauth:
      tokenUrls:
        - https://degateway.napix.gov.in:443/nic/cghs//oauth2/token
      refreshUrls: []
      authorizationUrls: []
  application-authentication:
    certificate: false
