host: delhigw.napix.gov.in
info:
  title: Parivahan
  version: 1.0.0
  x-ibm-name: umang-pending-data
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/parivahan
paths:
  /umang/pendingData:
    get:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      parameters:
        - in: query
          name: regnNo
          type: string
          required: true
      tags:
        - Umang pending data
schemes:
  - https
swagger: "2.0"
basePath: /nic/parivahan/mobileservices
security:
  - Client ID Header: []
    Client Secret Header: []
securityDefinitions:
  Client ID Header:
    in: header
    name: X-Client-Id
    type: apiKey
    x-key-type: client_id
  Client Secret Header:
    in: header
    name: X-Client-Secret
    type: apiKey
    x-key-type: client_secret
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://delhigw.napix.gov.in/nic/parivahan/mobileservices
      type:
        - production
        - development
  enforced: true
  testable: true
  application-authentication:
    certificate: false
