info:
  title: LGD
  version: 1.0.0
  x-ibm-name: activelocalgovernmentsetupofstate
  description: To fetch all the active Local Government Setups of a State in Local
    Government directory (LGD) available till date, in the required format.
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/lgd
paths:
  /state/{stateCode}/localGovernmentSetup/v1/status/active:
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: success
      parameters:
        - in: path
          name: stateCode
          schema:
            type: integer
          required: true
      tags:
        - Activelocalgovernmentsetupofstate
openapi: 3.0.0
servers:
  - url: https://delhigw.napix.gov.in/nic/lgd
    description: LGD Vanity Endpoint
security:
  - clientID: []
    clientSecret: []
components:
  schemas:
    code:
      type: integer
  securitySchemes:
    clientID:
      in: header
      name: X-IBM-Client-Id
      type: apiKey
      x-key-type: client_id
    clientSecret:
      in: header
      name: X-IBM-Client-Secret
      type: apiKey
      x-key-type: client_secret
x-ibm-endpoints:
  - url: https://delhigw.napix.gov.in/nic/lgd
    type:
      - production
      - development
    description: LGD Vanity Endpoint
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  enforced: true
  testable: true
