openapi: 3.0.3
info:  
  title: Board of Secondary Education, Odisha, Odisha
  description:  >- 
                The Board of Secondary Education, Odisha (BSE) is a board of education for public and private schools under the state government of Odisha. Digilocker is integrated with the BSE web application, which will provide the following services to the students who have passed 10th from BSE, Odisha  From 2011 to 2020 year(s):  1. Passing Certificate  2. Marksheet
  termsOfService: https://apisetu.gov.in/api-policy
  version: 3.0.0
servers:
  - url: 'https://apisetu.gov.in/certificate/v3/bse'
paths:
  
  /spcer:
    post:
      tags:
        - APIs
      summary: Class X / Matriculation Passing Certificate
      description: API to verify Class X / Matriculation Passing Certificate.
      security:
        - clientId: []
          apiKey: []
      operationId: spcer
      requestBody:
        description: Request format
        content:
          application/json:
            schema:
              type: object
              required:
                - txnId
                - format
              properties:
                txnId:
                  type: string
                  format: uuid
                  description: A unique transaction id for this request in UUID format. It is used for tracking the request.
                  example: "f7f1469c-29b0-4325-9dfc-c567200a70f7"
                format:
                  type: string
                  description: The format of the certificate in response.
                  enum:
                    - xml
                    
                    - pdf
                    
                    
                certificateParameters:
                  type: object
                  required:
                    - Examtype
                    - Rollno
                    - Userdob
                    - Passingyear
                    
                    - FullName
                    
                    - GENDER
                      
                  properties:
                    Examtype:
                      type: string
                      description: Exam Type
                      example: "Annual,Supplemantary"
                       
                    
                    Rollno:
                      type: string
                      description: Roll No
                      example: "05gf502"
                       
                    
                    Userdob:
                      type: string
                      description: DOB
                      example: "Format- DD/MM/YYYY e.g. 15/06/1989"
                       
                    
                    Passingyear:
                      type: string
                      description: Passing Year
                      example: "2011,2012,2013,2014,2015,2016,2017,2018,2019,2020"
                       
                    
                    
                    FullName:
                      type: string
                      description: Full name
                      example: "Sunil Kumar"
                    GENDER:
                      type: string
                      description: Gender - Male for male, Female for female and O for other
                      example: "Male"  
                consentArtifact:
                  $ref: '#/components/schemas/ConsentArtifactSchema'
      responses:
        '200':
          description: The certificate data in response body in PDF, XML or JSON format as requested in format parameter.
          content:
            application/xml:
              schema:  
                $ref: '#/components/schemas/AcademicCertificateSchema'  
            
            
            application/pdf:
              example: Response body contains contents of the certificate in PDF format.
            
            
            
        '400':
          $ref: '#/components/responses/400Error'
        '401':
          $ref: '#/components/responses/401Error'
        '404':
          $ref: '#/components/responses/404Error'
        '500':
          $ref: '#/components/responses/500Error'
        '502':
          $ref: '#/components/responses/502Error'
        '503':
          $ref: '#/components/responses/503Error'
        '504':
          $ref: '#/components/responses/504Error'
  
  /sscer:
    post:
      tags:
        - APIs
      summary: Class X Marksheet
      description: API to verify Class X Marksheet.
      security:
        - clientId: []
          apiKey: []
      operationId: sscer
      requestBody:
        description: Request format
        content:
          application/json:
            schema:
              type: object
              required:
                - txnId
                - format
              properties:
                txnId:
                  type: string
                  format: uuid
                  description: A unique transaction id for this request in UUID format. It is used for tracking the request.
                  example: "f7f1469c-29b0-4325-9dfc-c567200a70f7"
                format:
                  type: string
                  description: The format of the certificate in response.
                  enum:
                    - xml
                    
                    - pdf
                    
                    
                certificateParameters:
                  type: object
                  required:
                    - Examtype
                    - Rollno
                    - Userdob
                    - Passingyear
                    
                    - FullName
                    
                    - GENDER
                      
                  properties:
                    Examtype:
                      type: string
                      description: Exam Type
                      example: "Annual,Supplemantary"
                       
                    
                    Rollno:
                      type: string
                      description: Roll No
                      example: "05gf502"
                       
                    
                    Userdob:
                      type: string
                      description: DOB
                      example: "Format- DD/MM/YYYY e.g. 15/06/1989"
                       
                    
                    Passingyear:
                      type: string
                      description: Passing Year
                      example: "2011,2012,2013,2014,2015,2016,2017,2018,2019,2020"
                       
                    
                    
                    FullName:
                      type: string
                      description: Full name
                      example: "Sunil Kumar"
                    GENDER:
                      type: string
                      description: Gender - Male for male, Female for female and O for other
                      example: "Male"  
                consentArtifact:
                  $ref: '#/components/schemas/ConsentArtifactSchema'
      responses:
        '200':
          description: The certificate data in response body in PDF, XML or JSON format as requested in format parameter.
          content:
            application/xml:
              schema:  
                $ref: '#/components/schemas/AcademicCertificateSchema'  
            
            
            application/pdf:
              example: Response body contains contents of the certificate in PDF format.
            
            
            
        '400':
          $ref: '#/components/responses/400Error'
        '401':
          $ref: '#/components/responses/401Error'
        '404':
          $ref: '#/components/responses/404Error'
        '500':
          $ref: '#/components/responses/500Error'
        '502':
          $ref: '#/components/responses/502Error'
        '503':
          $ref: '#/components/responses/503Error'
        '504':
          $ref: '#/components/responses/504Error'
  
components:
  schemas:
    ConsentArtifactSchema:
      $ref: './common/ConsentArtifactSchema.yaml#/ConsentArtifactSchema'
    AcademicCertificateSchema:
      $ref: './common/AcademicCertificateSchema.yaml#/AcademicCertificateSchema'
          
  responses:
    400Error:
      $ref: './common/ErrorResponse.yaml#/400Error'
    401Error:
      $ref: './common/ErrorResponse.yaml#/401Error'
    404Error:
      $ref: './common/ErrorResponse.yaml#/404Error'
    500Error:
      $ref: './common/ErrorResponse.yaml#/500Error'
    502Error:
      $ref: './common/ErrorResponse.yaml#/502Error'
    503Error:
      $ref: './common/ErrorResponse.yaml#/503Error'
    504Error:
      $ref: './common/ErrorResponse.yaml#/504Error'
  securitySchemes:
    clientId:
      type: apiKey
      in: header
      name: X-APISETU-CLIENTID
    apiKey:
      type: apiKey
      in: header
      name: X-APISETU-APIKEY