info:
  title: LGD
  version: 1.0.0
  x-ibm-name: assemblyconstituency
  description: To fetch the Local Government Directory (LGD) Codes and additional
    information of active versions of all **Assembly Constituencies** of India
    available till date.
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/lgd
paths:
  /assemblyConstituency/v1:
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: success
      tags:
        - Assemblyconstituency
openapi: 3.0.0
servers:
  - url: https://delhigw.napix.gov.in/nic/lgd
    description: LGD Vanity Endpoint
security:
  - clientID: []
    clientSecret: []
components:
  securitySchemes:
    clientID:
      in: header
      name: X-IBM-Client-Id
      type: apiKey
      x-key-type: client_id
    clientSecret:
      in: header
      name: X-IBM-Client-Secret
      type: apiKey
      x-key-type: client_secret
x-ibm-endpoints:
  - url: https://delhigw.napix.gov.in/nic/lgd
    type:
      - production
      - development
    description: LGD Vanity Endpoint
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  enforced: true
  testable: true
