host: delhigw.napix.gov.in
info:
  title: CGHS
  version: 1.0.0
  x-ibm-name: insertaptdetails
  description: This API save details of CGHS beneficiaries when they Book any
    appointment like Doctor, City, Dispensary, Slot, Mobile etc.
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/cghs
tags:
  - name: Save Appointment Details
paths:
  /insertaptdetails:
    post:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      tags:
        - Insertaptdetails
    parameters:
      - in: body
        name: insertaptdetailsPara
        schema:
          type: object
          title: insertaptdetailsSchema
          properties:
            benId:
              type: string
            doctor:
              type: string
            aptDate:
              type: string
            endSlot:
              type: string
            cityCode:
              type: string
            dispCode:
              type: string
            mobileNo:
              type: string
            aptTypeId:
              type: string
            startSlot:
              type: string
            latestToken:
              type: string
            initialToken:
              type: string
            specialtyCode:
              type: string
        required: true
schemes:
  - https
swagger: "2.0"
basePath: /nic/cghs/insertaptdetails
security:
  - oauth:
      - napix
securityDefinitions:
  oauth:
    flow: application
    type: oauth2
    scopes:
      napix: ""
    tokenUrl: //oauth2/token
    x-ibm-oauth-provider: nic-oauth-provider-application-grant-type
  clientIdHeader:
    in: header
    name: X-IBM-Client-Id
    type: apiKey
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://delhigw.napix.gov.in/nic/cghs/insertaptdetails
      type:
        - production
        - development
  enforced: true
  testable: true
  oauth-servers:
    oauth:
      tokenUrls:
        - https://degateway.napix.gov.in:443/nic/cghs//oauth2/token
      refreshUrls: []
      authorizationUrls: []
  application-authentication:
    certificate: false
