host: delhigw.napix.gov.in
info:
  title: Dedupe
  version: "1.0"
  x-ibm-name: dedupestatusreport
  description: Dedupe Status Report
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/dedupe
tags:
  - name: transaction
    description: transaction
paths:
  /api/transaction/getDedupeStatusReport:
    post:
      tags:
        - Dedupestatusreport
      summary: DedupeStatusReport
      consumes:
        - application/json
      produces:
        - "*/*"
      responses:
        "200":
          schema:
            type: array
            items:
              type: object
              title: DedupeStatusReport
              properties:
                login_id:
                  type: integer
                  format: int32
                report_id:
                  type: integer
                  format: int32
                dedupe_end:
                  type: object
                  title: Timestamp
                  properties:
                    day:
                      type: integer
                      format: int32
                    date:
                      type: integer
                      format: int32
                    time:
                      type: integer
                      format: int64
                    year:
                      type: integer
                      format: int32
                    hours:
                      type: integer
                      format: int32
                    month:
                      type: integer
                      format: int32
                    nanos:
                      type: integer
                      format: int32
                    minutes:
                      type: integer
                      format: int32
                    seconds:
                      type: integer
                      format: int32
                    timezoneOffset:
                      type: integer
                      format: int32
                project_id:
                  type: integer
                  format: int32
                preproc_end:
                  type: object
                  title: Timestamp
                  properties:
                    day:
                      type: integer
                      format: int32
                    date:
                      type: integer
                      format: int32
                    time:
                      type: integer
                      format: int64
                    year:
                      type: integer
                      format: int32
                    hours:
                      type: integer
                      format: int32
                    month:
                      type: integer
                      format: int32
                    nanos:
                      type: integer
                      format: int32
                    minutes:
                      type: integer
                      format: int32
                    seconds:
                      type: integer
                      format: int32
                    timezoneOffset:
                      type: integer
                      format: int32
                dedupe_start:
                  type: object
                  title: Timestamp
                  properties:
                    day:
                      type: integer
                      format: int32
                    date:
                      type: integer
                      format: int32
                    time:
                      type: integer
                      format: int64
                    year:
                      type: integer
                      format: int32
                    hours:
                      type: integer
                      format: int32
                    month:
                      type: integer
                      format: int32
                    nanos:
                      type: integer
                      format: int32
                    minutes:
                      type: integer
                      format: int32
                    seconds:
                      type: integer
                      format: int32
                    timezoneOffset:
                      type: integer
                      format: int32
                preproc_start:
                  type: object
                  title: Timestamp
                  properties:
                    day:
                      type: integer
                      format: int32
                    date:
                      type: integer
                      format: int32
                    time:
                      type: integer
                      format: int64
                    year:
                      type: integer
                      format: int32
                    hours:
                      type: integer
                      format: int32
                    month:
                      type: integer
                      format: int32
                    nanos:
                      type: integer
                      format: int32
                    minutes:
                      type: integer
                      format: int32
                    seconds:
                      type: integer
                      format: int32
                    timezoneOffset:
                      type: integer
                      format: int32
                total_records:
                  type: integer
                  format: int32
                application_id:
                  type: integer
                  format: int64
                data_import_end:
                  type: object
                  title: Timestamp
                  properties:
                    day:
                      type: integer
                      format: int32
                    date:
                      type: integer
                      format: int32
                    time:
                      type: integer
                      format: int64
                    year:
                      type: integer
                      format: int32
                    hours:
                      type: integer
                      format: int32
                    month:
                      type: integer
                      format: int32
                    nanos:
                      type: integer
                      format: int32
                    minutes:
                      type: integer
                      format: int32
                    seconds:
                      type: integer
                      format: int32
                    timezoneOffset:
                      type: integer
                      format: int32
                matched_records:
                  type: integer
                  format: int32
                data_import_start:
                  type: object
                  title: Timestamp
                  properties:
                    day:
                      type: integer
                      format: int32
                    date:
                      type: integer
                      format: int32
                    time:
                      type: integer
                      format: int64
                    year:
                      type: integer
                      format: int32
                    hours:
                      type: integer
                      format: int32
                    month:
                      type: integer
                      format: int32
                    nanos:
                      type: integer
                      format: int32
                    minutes:
                      type: integer
                      format: int32
                    seconds:
                      type: integer
                      format: int32
                    timezoneOffset:
                      type: integer
                      format: int32
          description: OK
        "201":
          description: Created
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
      parameters:
        - in: header
          name: application_id
          type: integer
          format: int64
          required: true
          description: application_id
        - in: header
          name: login_id
          type: integer
          format: int32
          required: true
          description: login_id
        - in: header
          name: project_id
          type: integer
          format: int32
          required: true
          description: project_id
      operationId: DedupeStatusReportUsingPOST
schemes:
  - https
swagger: "2.0"
basePath: /nic/dedupe
security:
  - Oauth:
      - napix
definitions:
  Timestamp:
    type: object
    title: Timestamp
    properties:
      day:
        type: integer
        format: int32
      date:
        type: integer
        format: int32
      time:
        type: integer
        format: int64
      year:
        type: integer
        format: int32
      hours:
        type: integer
        format: int32
      month:
        type: integer
        format: int32
      nanos:
        type: integer
        format: int32
      minutes:
        type: integer
        format: int32
      seconds:
        type: integer
        format: int32
      timezoneOffset:
        type: integer
        format: int32
  DedupeStatusReport:
    type: object
    title: DedupeStatusReport
    properties:
      login_id:
        type: integer
        format: int32
      report_id:
        type: integer
        format: int32
      dedupe_end:
        type: object
        title: Timestamp
        properties:
          day:
            type: integer
            format: int32
          date:
            type: integer
            format: int32
          time:
            type: integer
            format: int64
          year:
            type: integer
            format: int32
          hours:
            type: integer
            format: int32
          month:
            type: integer
            format: int32
          nanos:
            type: integer
            format: int32
          minutes:
            type: integer
            format: int32
          seconds:
            type: integer
            format: int32
          timezoneOffset:
            type: integer
            format: int32
      project_id:
        type: integer
        format: int32
      preproc_end:
        type: object
        title: Timestamp
        properties:
          day:
            type: integer
            format: int32
          date:
            type: integer
            format: int32
          time:
            type: integer
            format: int64
          year:
            type: integer
            format: int32
          hours:
            type: integer
            format: int32
          month:
            type: integer
            format: int32
          nanos:
            type: integer
            format: int32
          minutes:
            type: integer
            format: int32
          seconds:
            type: integer
            format: int32
          timezoneOffset:
            type: integer
            format: int32
      dedupe_start:
        type: object
        title: Timestamp
        properties:
          day:
            type: integer
            format: int32
          date:
            type: integer
            format: int32
          time:
            type: integer
            format: int64
          year:
            type: integer
            format: int32
          hours:
            type: integer
            format: int32
          month:
            type: integer
            format: int32
          nanos:
            type: integer
            format: int32
          minutes:
            type: integer
            format: int32
          seconds:
            type: integer
            format: int32
          timezoneOffset:
            type: integer
            format: int32
      preproc_start:
        type: object
        title: Timestamp
        properties:
          day:
            type: integer
            format: int32
          date:
            type: integer
            format: int32
          time:
            type: integer
            format: int64
          year:
            type: integer
            format: int32
          hours:
            type: integer
            format: int32
          month:
            type: integer
            format: int32
          nanos:
            type: integer
            format: int32
          minutes:
            type: integer
            format: int32
          seconds:
            type: integer
            format: int32
          timezoneOffset:
            type: integer
            format: int32
      total_records:
        type: integer
        format: int32
      application_id:
        type: integer
        format: int64
      data_import_end:
        type: object
        title: Timestamp
        properties:
          day:
            type: integer
            format: int32
          date:
            type: integer
            format: int32
          time:
            type: integer
            format: int64
          year:
            type: integer
            format: int32
          hours:
            type: integer
            format: int32
          month:
            type: integer
            format: int32
          nanos:
            type: integer
            format: int32
          minutes:
            type: integer
            format: int32
          seconds:
            type: integer
            format: int32
          timezoneOffset:
            type: integer
            format: int32
      matched_records:
        type: integer
        format: int32
      data_import_start:
        type: object
        title: Timestamp
        properties:
          day:
            type: integer
            format: int32
          date:
            type: integer
            format: int32
          time:
            type: integer
            format: int64
          year:
            type: integer
            format: int32
          hours:
            type: integer
            format: int32
          month:
            type: integer
            format: int32
          nanos:
            type: integer
            format: int32
          minutes:
            type: integer
            format: int32
          seconds:
            type: integer
            format: int32
          timezoneOffset:
            type: integer
            format: int32
securityDefinitions:
  Oauth:
    flow: application
    type: oauth2
    scopes:
      napix: ""
    tokenUrl: //oauth2/token
    x-ibm-oauth-provider: nic-oauth-provider-application-grant-type
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://delhigw.napix.gov.in/nic/dedupe
      type:
        - production
        - development
  enforced: true
  testable: true
  oauth-servers:
    Oauth:
      tokenUrls:
        - https://degateway.napix.gov.in:443/nic/dedupe//oauth2/token
      refreshUrls: []
      authorizationUrls: []
  application-authentication:
    certificate: false
