info:
  title: LGD
  version: 1.0.0
  x-ibm-name: localbodiesbystate
  description: >
    To fetch the Local Government Directory (LGD) Codes and additional
    information of all versions of all **Localbodies** of a particular state
    using the LGD state code as input parameter.
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/lgd
paths:
  /state/{stateCode}/localbodies/v1/page/{page}:
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: success
      parameters:
        - in: path
          name: stateCode
          schema:
            type: integer
          required: true
        - in: path
          name: page
          schema:
            type: integer
          required: true
      tags:
        - Localbodiesbystate
openapi: 3.0.0
servers:
  - url: https://delhigw.napix.gov.in/nic/lgd
    description: LGD Vanity Endpoint
security:
  - clientID: []
    clientSecret: []
components:
  schemas:
    code:
      type: integer
    page:
      type: integer
  securitySchemes:
    clientID:
      in: header
      name: X-IBM-Client-Id
      type: apiKey
      x-key-type: client_id
    clientSecret:
      in: header
      name: X-IBM-Client-Secret
      type: apiKey
      x-key-type: client_secret
x-ibm-endpoints:
  - url: https://delhigw.napix.gov.in/nic/lgd
    type:
      - production
      - development
    description: LGD Vanity Endpoint
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  enforced: true
  testable: true
