host: wbgw.napix.gov.in
info:
  title: Backward Class Welfare Department, West Bengal
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/wb/bcwd
  version: 1.0.0
  x-ibm-name: certtificate-details
  description: The API is a data driven and fetches the certificate details from
    the Caste Certificate Portal of BCWD, Government of West Bengal. The API
    takes certificate number as input and returns certificate details as present
    in the portal in the form of a JSON response. It is published for
    consumption of the stakeholders as approved by the department.
paths:
  /certdet:
    post:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      parameters:
        - in: body
          name: certno
          schema:
            type: string
            title: certno
            maxLength: 50
            minLength: 6
          required: true
      tags:
        - Certtificate details
    parameters: []
schemes:
  - https
swagger: "2.0"
basePath: /wb/bcwd/certtificate_api
security:
  - client-id: []
    client-secret: []
securityDefinitions:
  client-id:
    in: header
    name: client-id
    type: apiKey
    x-key-type: client_id
  client-secret:
    in: header
    name: client-secret
    type: apiKey
    x-key-type: client_secret
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://wbgw.napix.gov.in/wb/bcwd/certtificate_api
      type:
        - production
        - development
  enforced: true
  testable: true
  application-authentication: {}
