host: delhigw.napix.gov.in
info:
  title: Dedupe
  version: "1.0"
  x-ibm-name: msgnotification
  description: Msg Notification
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/dedupe
tags:
  - name: transaction
    description: transaction
paths:
  /api/transaction/MsgNotification:
    post:
      tags:
        - Msgnotification
      summary: MsgNotification
      consumes:
        - application/json
      produces:
        - "*/*"
      responses:
        "200":
          schema:
            type: array
            items:
              type: object
              title: MsgNotification
              properties:
                msg_id:
                  type: integer
                  format: int32
                msg_desc:
                  type: string
                created_on:
                  type: object
                  title: Timestamp
                  properties:
                    day:
                      type: integer
                      format: int32
                    date:
                      type: integer
                      format: int32
                    time:
                      type: integer
                      format: int64
                    year:
                      type: integer
                      format: int32
                    hours:
                      type: integer
                      format: int32
                    month:
                      type: integer
                      format: int32
                    nanos:
                      type: integer
                      format: int32
                    minutes:
                      type: integer
                      format: int32
                    seconds:
                      type: integer
                      format: int32
                    timezoneOffset:
                      type: integer
                      format: int32
                msg_type_name:
                  type: string
          description: OK
        "201":
          description: Created
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
      parameters:
        - in: header
          name: msg_id
          type: integer
          format: int32
          required: true
          description: msg_id
      operationId: MsgNotificationUsingPOST
schemes:
  - https
swagger: "2.0"
basePath: /nic/dedupe
security:
  - Oauth:
      - napix
definitions:
  Timestamp:
    type: object
    title: Timestamp
    properties:
      day:
        type: integer
        format: int32
      date:
        type: integer
        format: int32
      time:
        type: integer
        format: int64
      year:
        type: integer
        format: int32
      hours:
        type: integer
        format: int32
      month:
        type: integer
        format: int32
      nanos:
        type: integer
        format: int32
      minutes:
        type: integer
        format: int32
      seconds:
        type: integer
        format: int32
      timezoneOffset:
        type: integer
        format: int32
  MsgNotification:
    type: object
    title: MsgNotification
    properties:
      msg_id:
        type: integer
        format: int32
      msg_desc:
        type: string
      created_on:
        type: object
        title: Timestamp
        properties:
          day:
            type: integer
            format: int32
          date:
            type: integer
            format: int32
          time:
            type: integer
            format: int64
          year:
            type: integer
            format: int32
          hours:
            type: integer
            format: int32
          month:
            type: integer
            format: int32
          nanos:
            type: integer
            format: int32
          minutes:
            type: integer
            format: int32
          seconds:
            type: integer
            format: int32
          timezoneOffset:
            type: integer
            format: int32
      msg_type_name:
        type: string
securityDefinitions:
  Oauth:
    flow: application
    type: oauth2
    scopes:
      napix: ""
    tokenUrl: //oauth2/token
    x-ibm-oauth-provider: nic-oauth-provider-application-grant-type
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://delhigw.napix.gov.in/nic/dedupe
      type:
        - production
        - development
  enforced: true
  testable: true
  oauth-servers:
    Oauth:
      tokenUrls:
        - https://degateway.napix.gov.in:443/nic/dedupe//oauth2/token
      refreshUrls: []
      authorizationUrls: []
  application-authentication:
    certificate: false
