host: delhigw.napix.gov.in
info:
  title: Parivahan
  version: 1.0.0
  x-ibm-name: vahanc-api-update-mobile-api-save-data-from-with-mobile
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/parivahan
paths:
  /updatemobile/service/savedatafromwithmobile:
    post:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      tags:
        - Vahanc api update mobile api save data from with mobile
schemes:
  - https
swagger: "2.0"
basePath: /nic/parivahan/vahancapi
security:
  - Oauth2Token:
      - napix
securityDefinitions:
  clientID:
    in: header
    name: X-Client-Id
    type: apiKey
    x-key-type: client_id
  Oauth2Token:
    flow: application
    type: oauth2
    scopes:
      napix: napixScope
    tokenUrl: //oauth2/token
    x-ibm-oauth-provider: nic-oauth-provider-application-grant-type
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://delhigw.napix.gov.in/nic/parivahan/vahancapi
      type:
        - production
        - development
  enforced: true
  testable: true
  oauth-servers:
    Oauth2Token:
      tokenUrls:
        - https://degateway.napix.gov.in:443/nic/parivahan//oauth2/token
      refreshUrls: []
      authorizationUrls: []
  application-authentication:
    certificate: false
