openapi: 3.0.3
info:  
  title: Pt. Deendayal Upadhyay Memorial Health Science And Ayush University Of Chattisgarh, Chhattisgarh
  description:  >- 
                Pt. Deendayal Upadhyay Memorial Health Science And Ayush University Of Chattisgarh is issuing their Digital awards for the following years, through DigiLocker. These can be pulled by students into their DigiLocker accounts                   Degree - 2019                   Marksheet - 2019,2020,2021,2022                   Diploma -  NA                   Transcript - NA
  termsOfService: https://apisetu.gov.in/api-policy
  version: 3.0.0
servers:
  - url: 'https://apisetu.gov.in/certificate/v3/cghealthuniv'
paths:
  
  /dgcer:
    post:
      tags:
        - APIs
      summary: Degree/ Diploma Certificate
      description: API to verify Degree/ Diploma Certificate.
      security:
        - clientId: []
          apiKey: []
      operationId: dgcer
      requestBody:
        description: Request format
        content:
          application/json:
            schema:
              type: object
              required:
                - txnId
                - format
              properties:
                txnId:
                  type: string
                  format: uuid
                  description: A unique transaction id for this request in UUID format. It is used for tracking the request.
                  example: "f7f1469c-29b0-4325-9dfc-c567200a70f7"
                format:
                  type: string
                  description: The format of the certificate in response.
                  enum:
                    - pdf
                    
                    
                certificateParameters:
                  type: object
                  required:
                    - RROLL
                    - REGNO
                    - YEAR
                    
                    - FullName
                      
                  properties:
                    RROLL:
                      type: string
                      description: Roll No.
                      example: "1407XX"
                       
                    
                    REGNO:
                      type: string
                      description: Registration No.
                      example: "E-2/414"
                       
                    
                    YEAR:
                      type: string
                      description: Year
                      example: "2019,2020,2021,2022"
                       
                    
                    
                    FullName:
                      type: string
                      description: Full name
                      example: "Sunil Kumar"  
                consentArtifact:
                  $ref: '#/components/schemas/ConsentArtifactSchema'
      responses:
        '200':
          description: The certificate data in response body in PDF, XML or JSON format as requested in format parameter.
          content:
            application/pdf:
              example: Response body contains contents of the certificate in PDF format.
            
            
            
        '400':
          $ref: '#/components/responses/400Error'
        '401':
          $ref: '#/components/responses/401Error'
        '404':
          $ref: '#/components/responses/404Error'
        '500':
          $ref: '#/components/responses/500Error'
        '502':
          $ref: '#/components/responses/502Error'
        '503':
          $ref: '#/components/responses/503Error'
        '504':
          $ref: '#/components/responses/504Error'
  
  /dgmst:
    post:
      tags:
        - APIs
      summary: Degree/ Diploma Marksheet
      description: API to verify Degree/ Diploma Marksheet.
      security:
        - clientId: []
          apiKey: []
      operationId: dgmst
      requestBody:
        description: Request format
        content:
          application/json:
            schema:
              type: object
              required:
                - txnId
                - format
              properties:
                txnId:
                  type: string
                  format: uuid
                  description: A unique transaction id for this request in UUID format. It is used for tracking the request.
                  example: "f7f1469c-29b0-4325-9dfc-c567200a70f7"
                format:
                  type: string
                  description: The format of the certificate in response.
                  enum:
                    - pdf
                    
                    
                certificateParameters:
                  type: object
                  required:
                    - RROLL
                    - REGNO
                    - MONTH
                    - YEAR
                    
                    - FullName
                      
                  properties:
                    RROLL:
                      type: string
                      description: Roll No.
                      example: "1300XX"
                       
                    
                    REGNO:
                      type: string
                      description: Registration No.
                      example: "D-8/XXX"
                       
                    
                    MONTH:
                      type: string
                      description: Month
                      example: "JANUARY,FEBRUARY,MARCH,APRIL,MAY,JUNE,JULY,AUGUST,SEPTEMBER,OCTOBER,NOVEMBER,DECEMBER"
                       
                    
                    YEAR:
                      type: string
                      description: Year
                      example: "2019,2020,2021,2022"
                       
                    
                    
                    FullName:
                      type: string
                      description: Full name
                      example: "Sunil Kumar"  
                consentArtifact:
                  $ref: '#/components/schemas/ConsentArtifactSchema'
      responses:
        '200':
          description: The certificate data in response body in PDF, XML or JSON format as requested in format parameter.
          content:
            application/pdf:
              example: Response body contains contents of the certificate in PDF format.
            
            
            
        '400':
          $ref: '#/components/responses/400Error'
        '401':
          $ref: '#/components/responses/401Error'
        '404':
          $ref: '#/components/responses/404Error'
        '500':
          $ref: '#/components/responses/500Error'
        '502':
          $ref: '#/components/responses/502Error'
        '503':
          $ref: '#/components/responses/503Error'
        '504':
          $ref: '#/components/responses/504Error'
  
components:
  schemas:
    ConsentArtifactSchema:
      $ref: './common/ConsentArtifactSchema.yaml#/ConsentArtifactSchema'
    AcademicCertificateSchema:
      $ref: './common/AcademicCertificateSchema.yaml#/AcademicCertificateSchema'
          
  responses:
    400Error:
      $ref: './common/ErrorResponse.yaml#/400Error'
    401Error:
      $ref: './common/ErrorResponse.yaml#/401Error'
    404Error:
      $ref: './common/ErrorResponse.yaml#/404Error'
    500Error:
      $ref: './common/ErrorResponse.yaml#/500Error'
    502Error:
      $ref: './common/ErrorResponse.yaml#/502Error'
    503Error:
      $ref: './common/ErrorResponse.yaml#/503Error'
    504Error:
      $ref: './common/ErrorResponse.yaml#/504Error'
  securitySchemes:
    clientId:
      type: apiKey
      in: header
      name: X-APISETU-CLIENTID
    apiKey:
      type: apiKey
      in: header
      name: X-APISETU-APIKEY