host: bgw.napix.gov.in
info:
  title: API Management for Tripura
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/trapi
  version: 1.0.0
  x-ibm-name: fooddeptrcverify
  description: This API of Food Department provides access to ration card details
    of citizens of Tripura. The API includes POST method for retrieving ration
    cards details  with input parameters as ration card number.
paths:
  /getmemberdetailsbyrcno:
    post:
      tags:
        - Fooddeptrcverify
      security: []
      responses:
        "200":
          schema:
            type: string
          description: success
      parameters:
        - in: body
          name: rcno
          schema:
            type: string
            title: rcno
          required: true
    parameters: []
schemes:
  - https
swagger: "2.0"
basePath: /nic/trapi/rcverify
security:
  - Oauth:
      - napix
parameters: {}
definitions: {}
securityDefinitions:
  Oauth:
    flow: application
    type: oauth2
    scopes:
      napix: NAPIX Scope
    tokenUrl: //oauth2/token
    x-ibm-oauth-provider: nic-oauth-provider-application-grant-type
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://bgw.napix.gov.in/nic/trapi/rcverify
      type:
        - production
        - development
      description: Bhubaneswar External Gateway
  enforced: true
  testable: true
  oauth-servers:
    Oauth:
      tokenUrls:
        - https://begateway.napix.gov.in:443/nic/trapi//oauth2/token
      refreshUrls: []
      authorizationUrls: []
  application-authentication:
    certificate: false
