host: delhigw.napix.gov.in
info:
  title: Reproductive & Child Health
  version: 1.0.0
  x-ibm-name: registerbeneficiary
  description: Common beneficiary Registration to get reference id to all entire
    health system for exchanging and integration the data
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/rch
paths:
  /:
    post:
      schemes:
        - https
      consumes:
        - application/json
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      parameters:
        - in: body
          name: body
          schema:
            type: object
            title: body
            properties:
              name:
                type: string
              anm_id:
                type: integer
              weight:
                type: number
              asha_id:
                type: integer
              ben_type:
                type: string
              lmp_date:
                type: string
              mobile_no:
                type: string
              source_id:
                type: integer
              created_by:
                type: integer
              ip_address:
                type: string
              state_code:
                type: integer
              abha_number:
                type: string
              taluka_code:
                type: string
              abha_address:
                type: string
              reference_id:
                type: integer
              village_code:
                type: integer
              date_of_birth:
                type: string
              district_code:
                type: integer
              registration_no:
                type: integer
              healthblock_code:
                type: integer
              registration_date:
                type: integer
              healthfacility_code:
                type: integer
              healthfacility_type:
                type: integer
              healthsubfacility_code:
                type: integer
          required: true
      tags:
        - Registerbeneficiary
schemes:
  - https
swagger: "2.0"
basePath: /nic/rch/registerbeneficiary
consumes:
  - application/json
security:
  - oauth:
      - napix
securityDefinitions:
  oauth:
    flow: application
    type: oauth2
    scopes:
      napix: NAPIX Scope
    tokenUrl: //oauth2/token
    x-ibm-oauth-provider: rch-oauth-provider-application-grant-type
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://delhigw.napix.gov.in/nic/rch/registerbeneficiary
      type:
        - production
        - development
  enforced: true
  testable: true
  oauth-servers:
    oauth:
      tokenUrls:
        - https://degateway.napix.gov.in:443/nic/rch//oauth2/token
      refreshUrls: []
      authorizationUrls: []
  application-authentication: {}
