openapi: 3.0.3
info:  
  title: Deshpande Foundation, Karnataka
  description:  >- 
                Deshpande Foundation has constantly worked towards recognizing and addressing the challenges of rural and semi-urban India. We focus on creating better, faster, inclusive and economical solutions in the areas of Agriculture, Micro-Entrepreneurship, Skilling, and Startups. We believe in navigating a unique path as a social enterprise, harnessing a blend of business excellence and compassion of not-for-profits.
  termsOfService: https://apisetu.gov.in/api-policy
  version: 3.0.0
servers:
  - url: 'https://apisetu.gov.in/certificate/v3/deshpandefoundation'
paths:
  
  /skcer:
    post:
      tags:
        - APIs
      summary: Skill Certificate
      description: API to verify Skill Certificate.
      security:
        - clientId: []
          apiKey: []
      operationId: skcer
      requestBody:
        description: Request format
        content:
          application/json:
            schema:
              type: object
              required:
                - txnId
                - format
              properties:
                txnId:
                  type: string
                  format: uuid
                  description: A unique transaction id for this request in UUID format. It is used for tracking the request.
                  example: "f7f1469c-29b0-4325-9dfc-c567200a70f7"
                format:
                  type: string
                  description: The format of the certificate in response.
                  enum:
                    - xml
                    
                    - pdf
                    
                    
                certificateParameters:
                  type: object
                  required:
                    - ApplicationNo
                    - ProgramType
                    - AcademicYear
                    
                    - GENDER
                    
                    - Mobile
                      
                  properties:
                    ApplicationNo:
                      type: string
                      description: Application No
                      example: "HB22011199"
                       
                    
                    ProgramType:
                      type: string
                      description: Program Type
                      example: ""
                       
                    
                    AcademicYear:
                      type: string
                      description: Registration Year
                      example: ""
                       
                    
                    
                    GENDER:
                      type: string
                      description: Gender - Male for male, Female for female and O for other
                      example: "Male"
                    Mobile:
                      type: string
                      description: Mobile No
                      example: "9876543210"
                      
                consentArtifact:
                  $ref: '#/components/schemas/ConsentArtifactSchema'
      responses:
        '200':
          description: The certificate data in response body in PDF, XML or JSON format as requested in format parameter.
          content:
            application/xml:
              schema:  
                $ref: '#/components/schemas/AcademicCertificateSchema'  
            
            
            application/pdf:
              example: Response body contains contents of the certificate in PDF format.
            
            
            
        '400':
          $ref: '#/components/responses/400Error'
        '401':
          $ref: '#/components/responses/401Error'
        '404':
          $ref: '#/components/responses/404Error'
        '500':
          $ref: '#/components/responses/500Error'
        '502':
          $ref: '#/components/responses/502Error'
        '503':
          $ref: '#/components/responses/503Error'
        '504':
          $ref: '#/components/responses/504Error'
  
components:
  schemas:
    ConsentArtifactSchema:
      $ref: './common/ConsentArtifactSchema.yaml#/ConsentArtifactSchema'
    AcademicCertificateSchema:
      $ref: './common/AcademicCertificateSchema.yaml#/AcademicCertificateSchema'
          
  responses:
    400Error:
      $ref: './common/ErrorResponse.yaml#/400Error'
    401Error:
      $ref: './common/ErrorResponse.yaml#/401Error'
    404Error:
      $ref: './common/ErrorResponse.yaml#/404Error'
    500Error:
      $ref: './common/ErrorResponse.yaml#/500Error'
    502Error:
      $ref: './common/ErrorResponse.yaml#/502Error'
    503Error:
      $ref: './common/ErrorResponse.yaml#/503Error'
    504Error:
      $ref: './common/ErrorResponse.yaml#/504Error'
  securitySchemes:
    clientId:
      type: apiKey
      in: header
      name: X-APISETU-CLIENTID
    apiKey:
      type: apiKey
      in: header
      name: X-APISETU-APIKEY