host: bgw.napix.gov.in
info:
  title: API Management for Tripura
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/trapi
  version: 1.0.0
  x-ibm-name: revenue_landrecords
  description: This API may be used to verify any Khatian or Plot that has been
    digitally recorded using the eJami Application
    (https://jami.tripura.gov.in). The API provides data about Khatian revenue,
    owners, plots, and other things.
paths:
  /khatian:
    get:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      parameters:
        - in: query
          name: lgd_village_code
          type: number
          required: true
        - in: query
          name: search_key
          type: string
          required: true
        - in: query
          name: search_val
          type: number
          required: true
      tags:
        - Revenue landrecords
schemes:
  - https
swagger: "2.0"
basePath: /nic/trapi/landrecords
security:
  - Client ID: []
    Client Key: []
    Oauth_Token:
      - napix
securityDefinitions:
  Client ID:
    in: header
    name: NIC-Client-ID
    type: apiKey
    x-key-type: client_id
  Client Key:
    in: header
    name: NIC-Client-Key
    type: apiKey
    x-key-type: client_secret
  Oauth_Token:
    flow: application
    type: oauth2
    scopes:
      napix: NAPIX Scope
    tokenUrl: //oauth2/token
    x-ibm-oauth-provider: nic-oauth-provider-application-grant-type
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://bgw.napix.gov.in/nic/trapi/landrecords
      type:
        - production
        - development
      description: Bhubaneswar External Gateway
  enforced: true
  testable: true
  oauth-servers:
    Oauth_Token:
      tokenUrls:
        - https://begateway.napix.gov.in:443/nic/trapi//oauth2/token
      refreshUrls: []
      authorizationUrls: []
  application-authentication:
    certificate: false
