info:
  title: Department Of Higher Education and School Education Department, Govt of
    West Bengal
  version: 1.0.0
  x-ibm-name: wbscc-authentication
  description: WBSCC ACCOUNT AUTHENTICATION SERVICE only used for account
    validation in WBSCC Mobile APP designed by WTL.
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/wb/education
paths:
  /authentication:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: success
        "401":
          description: NOT AUTHORIZED
        "404":
          description: DATA NOT FOUND
      parameters:
        - in: query
          name: stake_id
          schema:
            type: integer
            title: stake_id
            example: stake_id=6
            readOnly: true
            description: Stake Level ID
          example: stake_id=99
          required: true
          description: Stake User Level
        - in: query
          name: user_id
          schema:
            type: string
            title: user_id
            readOnly: true
            description: WBSCC USER ID
          example: user_id=WBSCC1234567890
          required: true
          description: User NAME
        - in: query
          name: password
          schema:
            type: string
            title: password
            example: password=samplepassword
            readOnly: true
            description: User Password
          example: password=abcd1234
          required: true
          description: PASSWORD
      tags:
        - Wbscc authentication
openapi: 3.0.0
servers:
  - url: https://wbgw.napix.gov.in/wb/education/wbscc
security:
  - clientID: []
    clientSecret: []
  - {}
components:
  securitySchemes:
    clientID:
      in: header
      name: X-NIC-Client-Id
      type: apiKey
      x-key-type: client_id
    clientSecret:
      in: header
      name: X-NIC-Client-Secret
      type: apiKey
      x-key-type: client_secret
x-ibm-endpoints:
  - url: https://wbgw.napix.gov.in/wb/education/wbscc
    type:
      - production
      - development
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  enforced: true
  testable: true
