info:
  title: Department Of Higher Education and School Education Department, Govt of
    West Bengal
  version: 1.0.0
  x-ibm-name: wbscc-application-details
  description: This API provides West Bengal Student Credit Card application form
    details by taking Application ID as Input.
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/wb/education
paths:
  /applicant_details:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: success
        "401":
          description: NOT AUTHORIZED
        "404":
          description: DATA NOT FOUND
      parameters:
        - in: query
          name: applicant_id
          schema:
            type: string
            title: applicant_id
            readOnly: true
            description: APLICATION ID
          example: applicant_id=WBSCC1234567890
          required: true
          description: APPLICATION ID
      tags:
        - Wbscc application details
openapi: 3.0.0
servers:
  - url: https://wbgw.napix.gov.in/wb/education/wbscc
security:
  - clientID: []
    clientSecret: []
components:
  securitySchemes:
    clientID:
      in: header
      name: X-NIC-Client-Id
      type: apiKey
      x-key-type: client_id
    clientSecret:
      in: header
      name: X-NIC-Client-Secret
      type: apiKey
      x-key-type: client_secret
x-ibm-endpoints:
  - url: https://wbgw.napix.gov.in/wb/education/wbscc
    type:
      - production
      - development
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  enforced: true
  testable: true
