host: delhigw.napix.gov.in
info:
  title: Parivahan
  version: 1.0.0
  x-ibm-name: irad-police-web-service
  description: Integrated Road Accident Database API
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/parivahan
paths:
  /service/info:
    post:
      tags:
        - Irad police web service
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      parameters:
        - in: formData
          name: username
          type: string
          required: true
        - in: formData
          name: password
          type: string
          required: true
        - in: formData
          name: accidentid
          type: string
          required: true
        - in: formData
          name: ln
          type: string
          required: true
        - in: formData
          name: data
          type: string
          required: true
schemes:
  - https
swagger: "2.0"
basePath: /nic/parivahan/iradservices
security:
  - clientID: []
  - Oauth2Token:
      - napix
securityDefinitions:
  clientID:
    in: header
    name: X-IBM-Client-Id
    type: apiKey
  Oauth2Token:
    flow: application
    type: oauth2
    scopes:
      napix: scope
    tokenUrl: //oauth2/token
    x-ibm-oauth-provider: nic-oauth-provider-application-grant-type
  clientsecret:
    in: header
    name: X-Client-Secret
    type: apiKey
    x-key-type: client_secret
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://delhigw.napix.gov.in/nic/parivahan/iradservices
      type:
        - production
        - development
  enforced: true
  testable: true
  oauth-servers:
    Oauth2Token:
      tokenUrls:
        - https://degateway.napix.gov.in:443/nic/parivahan//oauth2/token
      refreshUrls: []
      authorizationUrls: []
  application-authentication:
    certificate: false
