host: wb-gateway.napix.gov.in
info:
  title: Food & Supplies Department
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/wb/food-supplies
  version: 1.0.0
  x-ibm-name: wbulc-lc-info-via-aadhar
  description: API for fetching life certificate information by Aadhar number.
    This API is   JWT based. It can cater single data rendering only.
paths:
  /:
    post:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      parameters:
        - in: header
          name: Authorization
          type: string
          required: true
        - in: body
          name: body
          schema:
            type: object
            title: body
            properties:
              uidData:
                type: string
                title: uidData
              clientId:
                type: string
                title: clientId
              tokenRefId:
                type: string
                title: tokenRefId
              clientTxnNo:
                type: string
                title: clientTxnNo
          required: true
      tags:
        - Wbulc lc info via aadhar
schemes:
  - https
swagger: "2.0"
basePath: /wb/food-supplies/wbulc-lc-info-via-aadhar
security:
  - clientID: []
    clientSecret: []
securityDefinitions:
  clientID:
    in: header
    name: clientID
    type: apiKey
    x-key-type: client_id
  clientSecret:
    in: header
    name: clientSecret
    type: apiKey
    x-key-type: client_secret
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://wb-gateway.napix.gov.in/wb/food-supplies/wbulc-lc-info-via-aadhar
      type:
        - production
        - development
      description: ""
  enforced: true
  testable: true
  application-authentication: {}
