host: delhigw.napix.gov.in
info:
  title: Parivahan
  version: 1.0.0
  x-ibm-name: mparivahan-challan-list
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/parivahan
paths:
  /mparivahan-api/challanrcmapp:
    post:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      parameters:
        - in: header
          name: "Authorization "
          type: string
          required: false
      tags:
        - Mparivahan challan list
schemes:
  - https
swagger: "2.0"
basePath: /nic/parivahan/echallan
security:
  - Client ID Header: []
    Client Secret Header: []
securityDefinitions:
  Client ID Header:
    in: header
    name: X-Client-Id
    type: apiKey
    x-key-type: client_id
  Client Secret Header:
    in: header
    name: X-Client-Secret
    type: apiKey
    x-key-type: client_secret
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://delhigw.napix.gov.in/nic/parivahan/echallan
      type:
        - production
        - development
  enforced: true
  testable: true
  application-authentication:
    certificate: false
