host: delhigw.napix.gov.in
info:
  title: CGHS
  version: 1.0.0
  x-ibm-name: cghscityhco
  description: This API gives city-wise HCO ID and HCO name i.e health care
    organisation by providing the city information.
  contact:
    name: Provided by - NAPIX
    url: https://dev.napix.gov.in/nic/cghs
tags:
  - name: CGHS Hospital empanelled Hospital Name
paths:
  /cghsCityHco:
    get:
      consumes: []
      produces: []
      responses:
        "200":
          schema:
            type: string
          description: success
      parameters:
        - in: query
          name: cghsCityId
          type: string
          required: true
      tags:
        - Cghscityhco
    parameters: []
schemes:
  - https
swagger: "2.0"
basePath: /nic/cghs/cghscityhco
security:
  - oauth:
      - napix
securityDefinitions:
  oauth:
    flow: application
    type: oauth2
    scopes:
      napix: ""
    tokenUrl: //oauth2/token
    x-ibm-oauth-provider: nic-oauth-provider-application-grant-type
  clientIdHeader:
    in: header
    name: X-IBM-Client-Id
    type: apiKey
x-ibm-configuration:
  cors:
    enabled: true
  type: rest
  phase: realized
  servers:
    - url: https://delhigw.napix.gov.in/nic/cghs/cghscityhco
      type:
        - production
        - development
  enforced: true
  testable: true
  oauth-servers:
    oauth:
      tokenUrls:
        - https://degateway.napix.gov.in:443/nic/cghs//oauth2/token
      refreshUrls: []
      authorizationUrls: []
  application-authentication:
    certificate: false
