openapi: 3.0.3
info:  
  title: Jal Shakti, Jammu & Kashmir
  description:  >- 
                Jal Shakti Public Health Engineering Department provides 03 services which are to be integrated with DigiLocker. The services are:Application for water connection(Domestic), Application for water connection(Commercial)& Application for extraction of Ground water and e-billing of all these services thereof.
  termsOfService: https://apisetu.gov.in/api-policy
  version: 3.0.0
servers:
  - url: 'https://apisetu.gov.in/certificate/v3/jkphedwaterbilling'
paths:
  
  /tapcn:
    post:
      tags:
        - APIs
      summary: New Tap Connection
      description: API to verify New Tap Connection.
      security:
        - clientId: []
          apiKey: []
      operationId: tapcn
      requestBody:
        description: Request format
        content:
          application/json:
            schema:
              type: object
              required:
                - txnId
                - format
              properties:
                txnId:
                  type: string
                  format: uuid
                  description: A unique transaction id for this request in UUID format. It is used for tracking the request.
                  example: "f7f1469c-29b0-4325-9dfc-c567200a70f7"
                format:
                  type: string
                  description: The format of the certificate in response.
                  enum:
                    - pdf
                    
                    
                certificateParameters:
                  type: object
                  required:
                    - TYPE
                    - SUBDIVISION
                    - CONSUMERID
                    
                    - FullName
                      
                  properties:
                    TYPE:
                      type: string
                      description: TYPE
                      example: "BOREWELL CONNECTION CERTIFICATE,TAP CONNECTION CERTIFICATE"
                       
                    
                    SUBDIVISION:
                      type: string
                      description: SUBDIVISION
                      example: "Dhounthly,Bakshinagar,Muthi,Sitlee,Gandhinagar,Kunjwani,Narwal,SDO-1,SDO-3,City,Doodh Ganga,NWR"
                       
                    
                    CONSUMERID:
                      type: string
                      description: CONSUMER ID
                      example: "0101020160157"
                       
                    
                    
                    FullName:
                      type: string
                      description: Full name
                      example: "Sunil Kumar"  
                consentArtifact:
                  $ref: '#/components/schemas/ConsentArtifactSchema'
      responses:
        '200':
          description: The certificate data in response body in PDF, XML or JSON format as requested in format parameter.
          content:
            application/pdf:
              example: Response body contains contents of the certificate in PDF format.
            
            
            
        '400':
          $ref: '#/components/responses/400Error'
        '401':
          $ref: '#/components/responses/401Error'
        '404':
          $ref: '#/components/responses/404Error'
        '500':
          $ref: '#/components/responses/500Error'
        '502':
          $ref: '#/components/responses/502Error'
        '503':
          $ref: '#/components/responses/503Error'
        '504':
          $ref: '#/components/responses/504Error'
  
  /prcpt:
    post:
      tags:
        - APIs
      summary: Payment/ Premium Receipt
      description: API to verify Payment/ Premium Receipt.
      security:
        - clientId: []
          apiKey: []
      operationId: prcpt
      requestBody:
        description: Request format
        content:
          application/json:
            schema:
              type: object
              required:
                - txnId
                - format
              properties:
                txnId:
                  type: string
                  format: uuid
                  description: A unique transaction id for this request in UUID format. It is used for tracking the request.
                  example: "f7f1469c-29b0-4325-9dfc-c567200a70f7"
                format:
                  type: string
                  description: The format of the certificate in response.
                  enum:
                    - xml
                    
                    - pdf
                    
                    
                certificateParameters:
                  type: object
                  required:
                    - TYPE
                    - SUBDIVISION
                    - CONSUMERID
                    
                    - FullName
                      
                  properties:
                    TYPE:
                      type: string
                      description: SELECT TYPE
                      example: "WATER BILL PAYMENT RECEIPT"
                       
                    
                    SUBDIVISION:
                      type: string
                      description: subdivision
                      example: "Dhounthly,Bakshinagar,Muthi,Sitlee,Gandhinagar,Kunjwani,Narwal,SDO-1,SDO-3,City,Doodh Ganga,NWR  Dhounthly,Bakshinagar,Muthi,Sitlee,Gandhinagar,Kunjwani,Narwal,SDO-1,SDO-3,City,Doodh Ganga,NWR"
                       
                    
                    CONSUMERID:
                      type: string
                      description: Consumer Id
                      example: "0101020160353"
                       
                    
                    
                    FullName:
                      type: string
                      description: Full name
                      example: "Sunil Kumar"  
                consentArtifact:
                  $ref: '#/components/schemas/ConsentArtifactSchema'
      responses:
        '200':
          description: The certificate data in response body in PDF, XML or JSON format as requested in format parameter.
          content:
            application/xml:
              schema:  
                $ref: '#/components/schemas/AcademicCertificateSchema'  
            
            
            application/pdf:
              example: Response body contains contents of the certificate in PDF format.
            
            
            
        '400':
          $ref: '#/components/responses/400Error'
        '401':
          $ref: '#/components/responses/401Error'
        '404':
          $ref: '#/components/responses/404Error'
        '500':
          $ref: '#/components/responses/500Error'
        '502':
          $ref: '#/components/responses/502Error'
        '503':
          $ref: '#/components/responses/503Error'
        '504':
          $ref: '#/components/responses/504Error'
  
  /wtrbl:
    post:
      tags:
        - APIs
      summary: Water Bill/ Connection
      description: API to verify Water Bill/ Connection.
      security:
        - clientId: []
          apiKey: []
      operationId: wtrbl
      requestBody:
        description: Request format
        content:
          application/json:
            schema:
              type: object
              required:
                - txnId
                - format
              properties:
                txnId:
                  type: string
                  format: uuid
                  description: A unique transaction id for this request in UUID format. It is used for tracking the request.
                  example: "f7f1469c-29b0-4325-9dfc-c567200a70f7"
                format:
                  type: string
                  description: The format of the certificate in response.
                  enum:
                    - xml
                    
                    - pdf
                    
                    
                certificateParameters:
                  type: object
                  required:
                    - SUBDIVISION
                    - CONSUMERID
                    
                    - FullName
                      
                  properties:
                    SUBDIVISION:
                      type: string
                      description: Subdivision
                      example: "Dhounthly,Bakshinagar,Muthi,Sitlee,Gandhinagar,Kunjwani,Narwal,SDO-1,SDO-3,City,Doodh Ganga,NWR"
                       
                    
                    CONSUMERID:
                      type: string
                      description: Consumer ID
                      example: "0101020160157"
                       
                    
                    
                    FullName:
                      type: string
                      description: Full name
                      example: "Sunil Kumar"  
                consentArtifact:
                  $ref: '#/components/schemas/ConsentArtifactSchema'
      responses:
        '200':
          description: The certificate data in response body in PDF, XML or JSON format as requested in format parameter.
          content:
            application/xml:
              schema:  
                $ref: '#/components/schemas/AcademicCertificateSchema'  
            
            
            application/pdf:
              example: Response body contains contents of the certificate in PDF format.
            
            
            
        '400':
          $ref: '#/components/responses/400Error'
        '401':
          $ref: '#/components/responses/401Error'
        '404':
          $ref: '#/components/responses/404Error'
        '500':
          $ref: '#/components/responses/500Error'
        '502':
          $ref: '#/components/responses/502Error'
        '503':
          $ref: '#/components/responses/503Error'
        '504':
          $ref: '#/components/responses/504Error'
  
components:
  schemas:
    ConsentArtifactSchema:
      $ref: './common/ConsentArtifactSchema.yaml#/ConsentArtifactSchema'
    AcademicCertificateSchema:
      $ref: './common/AcademicCertificateSchema.yaml#/AcademicCertificateSchema'
          
  responses:
    400Error:
      $ref: './common/ErrorResponse.yaml#/400Error'
    401Error:
      $ref: './common/ErrorResponse.yaml#/401Error'
    404Error:
      $ref: './common/ErrorResponse.yaml#/404Error'
    500Error:
      $ref: './common/ErrorResponse.yaml#/500Error'
    502Error:
      $ref: './common/ErrorResponse.yaml#/502Error'
    503Error:
      $ref: './common/ErrorResponse.yaml#/503Error'
    504Error:
      $ref: './common/ErrorResponse.yaml#/504Error'
  securitySchemes:
    clientId:
      type: apiKey
      in: header
      name: X-APISETU-CLIENTID
    apiKey:
      type: apiKey
      in: header
      name: X-APISETU-APIKEY