openapi: 3.0.3
info:  
  title: ManipalCigna Health Insurance Company Limited, Maharashtra
  description:  >- 
                APIs provided by ManipalCigna Health Insurance Company Limited, Maharashtra.
  termsOfService: https://apisetu.gov.in/api-policy
  version: 3.0.0
servers:
  - url: 'https://apisetu.gov.in/certificate/v3/manipalcigna'
paths:
  
  /tchip:
    post:
      tags:
        - APIs
      summary: 80D Certificate
      description: API to verify 80D Certificate.
      security:
        - clientId: []
          apiKey: []
      operationId: tchip
      requestBody:
        description: Request format
        content:
          application/json:
            schema:
              type: object
              required:
                - txnId
                - format
              properties:
                txnId:
                  type: string
                  format: uuid
                  description: A unique transaction id for this request in UUID format. It is used for tracking the request.
                  example: "f7f1469c-29b0-4325-9dfc-c567200a70f7"
                format:
                  type: string
                  description: The format of the certificate in response.
                  enum:
                    - pdf
                    
                    
                certificateParameters:
                  type: object
                  required:
                    - PolicyNumber
                    
                    - DOB
                      
                  properties:
                    PolicyNumber:
                      type: string
                      description: PolicyNumber
                      example: "AROSAN050000002"
                       
                    
                    
                    DOB:
                      type: string
                      description: Date of birth in DD-MM-YYYY format
                      example: "31-12-1980"  
                consentArtifact:
                  $ref: '#/components/schemas/ConsentArtifactSchema'
      responses:
        '200':
          description: The certificate data in response body in PDF, XML or JSON format as requested in format parameter.
          content:
            application/pdf:
              example: Response body contains contents of the certificate in PDF format.
            
            
            
        '400':
          $ref: '#/components/responses/400Error'
        '401':
          $ref: '#/components/responses/401Error'
        '404':
          $ref: '#/components/responses/404Error'
        '500':
          $ref: '#/components/responses/500Error'
        '502':
          $ref: '#/components/responses/502Error'
        '503':
          $ref: '#/components/responses/503Error'
        '504':
          $ref: '#/components/responses/504Error'
  
  /grout:
    post:
      tags:
        - APIs
      summary: Grant/ Renewal of a Unit
      description: API to verify Grant/ Renewal of a Unit.
      security:
        - clientId: []
          apiKey: []
      operationId: grout
      requestBody:
        description: Request format
        content:
          application/json:
            schema:
              type: object
              required:
                - txnId
                - format
              properties:
                txnId:
                  type: string
                  format: uuid
                  description: A unique transaction id for this request in UUID format. It is used for tracking the request.
                  example: "f7f1469c-29b0-4325-9dfc-c567200a70f7"
                format:
                  type: string
                  description: The format of the certificate in response.
                  enum:
                    - pdf
                    
                    
                certificateParameters:
                  type: object
                  required:
                    - PolicyNumber
                    
                    - DOB
                      
                  properties:
                    PolicyNumber:
                      type: string
                      description: PolicyNumber
                      example: "PROHLR010009511"
                       
                    
                    
                    DOB:
                      type: string
                      description: Date of birth in DD-MM-YYYY format
                      example: "31-12-1980"  
                consentArtifact:
                  $ref: '#/components/schemas/ConsentArtifactSchema'
      responses:
        '200':
          description: The certificate data in response body in PDF, XML or JSON format as requested in format parameter.
          content:
            application/pdf:
              example: Response body contains contents of the certificate in PDF format.
            
            
            
        '400':
          $ref: '#/components/responses/400Error'
        '401':
          $ref: '#/components/responses/401Error'
        '404':
          $ref: '#/components/responses/404Error'
        '500':
          $ref: '#/components/responses/500Error'
        '502':
          $ref: '#/components/responses/502Error'
        '503':
          $ref: '#/components/responses/503Error'
        '504':
          $ref: '#/components/responses/504Error'
  
  /rsbyc:
    post:
      tags:
        - APIs
      summary: Health Card/ Certificate
      description: API to verify Health Card/ Certificate.
      security:
        - clientId: []
          apiKey: []
      operationId: rsbyc
      requestBody:
        description: Request format
        content:
          application/json:
            schema:
              type: object
              required:
                - txnId
                - format
              properties:
                txnId:
                  type: string
                  format: uuid
                  description: A unique transaction id for this request in UUID format. It is used for tracking the request.
                  example: "f7f1469c-29b0-4325-9dfc-c567200a70f7"
                format:
                  type: string
                  description: The format of the certificate in response.
                  enum:
                    - pdf
                    
                    
                certificateParameters:
                  type: object
                  required:
                    - PolicyNumber
                    
                    - DOB
                      
                  properties:
                    PolicyNumber:
                      type: string
                      description: PolicyNumber
                      example: "AROSAN050000001"
                       
                    
                    
                    DOB:
                      type: string
                      description: Date of birth in DD-MM-YYYY format
                      example: "31-12-1980"  
                consentArtifact:
                  $ref: '#/components/schemas/ConsentArtifactSchema'
      responses:
        '200':
          description: The certificate data in response body in PDF, XML or JSON format as requested in format parameter.
          content:
            application/pdf:
              example: Response body contains contents of the certificate in PDF format.
            
            
            
        '400':
          $ref: '#/components/responses/400Error'
        '401':
          $ref: '#/components/responses/401Error'
        '404':
          $ref: '#/components/responses/404Error'
        '500':
          $ref: '#/components/responses/500Error'
        '502':
          $ref: '#/components/responses/502Error'
        '503':
          $ref: '#/components/responses/503Error'
        '504':
          $ref: '#/components/responses/504Error'
  
  /gicer:
    post:
      tags:
        - APIs
      summary: Insurance - Group
      description: API to verify Insurance - Group.
      security:
        - clientId: []
          apiKey: []
      operationId: gicer
      requestBody:
        description: Request format
        content:
          application/json:
            schema:
              type: object
              required:
                - txnId
                - format
              properties:
                txnId:
                  type: string
                  format: uuid
                  description: A unique transaction id for this request in UUID format. It is used for tracking the request.
                  example: "f7f1469c-29b0-4325-9dfc-c567200a70f7"
                format:
                  type: string
                  description: The format of the certificate in response.
                  enum:
                    - pdf
                    
                    
                certificateParameters:
                  type: object
                  required:
                    - COINumber
                    
                    - DOB
                      
                  properties:
                    COINumber:
                      type: string
                      description: Policy Number
                      example: "100100009851"
                       
                    
                    
                    DOB:
                      type: string
                      description: Date of birth in DD-MM-YYYY format
                      example: "31-12-1980"  
                consentArtifact:
                  $ref: '#/components/schemas/ConsentArtifactSchema'
      responses:
        '200':
          description: The certificate data in response body in PDF, XML or JSON format as requested in format parameter.
          content:
            application/pdf:
              example: Response body contains contents of the certificate in PDF format.
            
            
            
        '400':
          $ref: '#/components/responses/400Error'
        '401':
          $ref: '#/components/responses/401Error'
        '404':
          $ref: '#/components/responses/404Error'
        '500':
          $ref: '#/components/responses/500Error'
        '502':
          $ref: '#/components/responses/502Error'
        '503':
          $ref: '#/components/responses/503Error'
        '504':
          $ref: '#/components/responses/504Error'
  
  /inend:
    post:
      tags:
        - APIs
      summary: Insurance Endorsements
      description: API to verify Insurance Endorsements.
      security:
        - clientId: []
          apiKey: []
      operationId: inend
      requestBody:
        description: Request format
        content:
          application/json:
            schema:
              type: object
              required:
                - txnId
                - format
              properties:
                txnId:
                  type: string
                  format: uuid
                  description: A unique transaction id for this request in UUID format. It is used for tracking the request.
                  example: "f7f1469c-29b0-4325-9dfc-c567200a70f7"
                format:
                  type: string
                  description: The format of the certificate in response.
                  enum:
                    - pdf
                    
                    
                certificateParameters:
                  type: object
                  required:
                    - PolicyNumber
                    - SRNumber
                    
                    - DOB
                      
                  properties:
                    PolicyNumber:
                      type: string
                      description: PolicyNumber
                      example: "LTPRCC410002455"
                       
                    
                    SRNumber:
                      type: string
                      description: SRNumber
                      example: "2018011400433"
                       
                    
                    
                    DOB:
                      type: string
                      description: Date of birth in DD-MM-YYYY format
                      example: "31-12-1980"  
                consentArtifact:
                  $ref: '#/components/schemas/ConsentArtifactSchema'
      responses:
        '200':
          description: The certificate data in response body in PDF, XML or JSON format as requested in format parameter.
          content:
            application/pdf:
              example: Response body contains contents of the certificate in PDF format.
            
            
            
        '400':
          $ref: '#/components/responses/400Error'
        '401':
          $ref: '#/components/responses/401Error'
        '404':
          $ref: '#/components/responses/404Error'
        '500':
          $ref: '#/components/responses/500Error'
        '502':
          $ref: '#/components/responses/502Error'
        '503':
          $ref: '#/components/responses/503Error'
        '504':
          $ref: '#/components/responses/504Error'
  
  /igend:
    post:
      tags:
        - APIs
      summary: Insurance Endorsements- Group
      description: API to verify Insurance Endorsements- Group.
      security:
        - clientId: []
          apiKey: []
      operationId: igend
      requestBody:
        description: Request format
        content:
          application/json:
            schema:
              type: object
              required:
                - txnId
                - format
              properties:
                txnId:
                  type: string
                  format: uuid
                  description: A unique transaction id for this request in UUID format. It is used for tracking the request.
                  example: "f7f1469c-29b0-4325-9dfc-c567200a70f7"
                format:
                  type: string
                  description: The format of the certificate in response.
                  enum:
                    - pdf
                    
                    
                certificateParameters:
                  type: object
                  required:
                    - COINumber
                    
                    - DOB
                      
                  properties:
                    COINumber:
                      type: string
                      description: Policy Number
                      example: "100100009851"
                       
                    
                    
                    DOB:
                      type: string
                      description: Date of birth in DD-MM-YYYY format
                      example: "31-12-1980"  
                consentArtifact:
                  $ref: '#/components/schemas/ConsentArtifactSchema'
      responses:
        '200':
          description: The certificate data in response body in PDF, XML or JSON format as requested in format parameter.
          content:
            application/pdf:
              example: Response body contains contents of the certificate in PDF format.
            
            
            
        '400':
          $ref: '#/components/responses/400Error'
        '401':
          $ref: '#/components/responses/401Error'
        '404':
          $ref: '#/components/responses/404Error'
        '500':
          $ref: '#/components/responses/500Error'
        '502':
          $ref: '#/components/responses/502Error'
        '503':
          $ref: '#/components/responses/503Error'
        '504':
          $ref: '#/components/responses/504Error'
  
  /podoc:
    post:
      tags:
        - APIs
      summary: Policy Document
      description: API to verify Policy Document.
      security:
        - clientId: []
          apiKey: []
      operationId: podoc
      requestBody:
        description: Request format
        content:
          application/json:
            schema:
              type: object
              required:
                - txnId
                - format
              properties:
                txnId:
                  type: string
                  format: uuid
                  description: A unique transaction id for this request in UUID format. It is used for tracking the request.
                  example: "f7f1469c-29b0-4325-9dfc-c567200a70f7"
                format:
                  type: string
                  description: The format of the certificate in response.
                  enum:
                    - pdf
                    
                    
                certificateParameters:
                  type: object
                  required:
                    - PolicyNumber
                    
                    - DOB
                      
                  properties:
                    PolicyNumber:
                      type: string
                      description: PolicyNumber
                      example: "PROTOP780000854"
                       
                    
                    
                    DOB:
                      type: string
                      description: Date of birth in DD-MM-YYYY format
                      example: "31-12-1980"  
                consentArtifact:
                  $ref: '#/components/schemas/ConsentArtifactSchema'
      responses:
        '200':
          description: The certificate data in response body in PDF, XML or JSON format as requested in format parameter.
          content:
            application/pdf:
              example: Response body contains contents of the certificate in PDF format.
            
            
            
        '400':
          $ref: '#/components/responses/400Error'
        '401':
          $ref: '#/components/responses/401Error'
        '404':
          $ref: '#/components/responses/404Error'
        '500':
          $ref: '#/components/responses/500Error'
        '502':
          $ref: '#/components/responses/502Error'
        '503':
          $ref: '#/components/responses/503Error'
        '504':
          $ref: '#/components/responses/504Error'
  
components:
  schemas:
    ConsentArtifactSchema:
      $ref: './common/ConsentArtifactSchema.yaml#/ConsentArtifactSchema'
    AcademicCertificateSchema:
      $ref: './common/AcademicCertificateSchema.yaml#/AcademicCertificateSchema'
          
  responses:
    400Error:
      $ref: './common/ErrorResponse.yaml#/400Error'
    401Error:
      $ref: './common/ErrorResponse.yaml#/401Error'
    404Error:
      $ref: './common/ErrorResponse.yaml#/404Error'
    500Error:
      $ref: './common/ErrorResponse.yaml#/500Error'
    502Error:
      $ref: './common/ErrorResponse.yaml#/502Error'
    503Error:
      $ref: './common/ErrorResponse.yaml#/503Error'
    504Error:
      $ref: './common/ErrorResponse.yaml#/504Error'
  securitySchemes:
    clientId:
      type: apiKey
      in: header
      name: X-APISETU-CLIENTID
    apiKey:
      type: apiKey
      in: header
      name: X-APISETU-APIKEY