openapi: 3.0.3
info:  
  title: Panjiyak Shiksha Vibhagiya Parikshayen Rajasthan, Bikaner, Rajasthan
  description:  >- 
                Panjiyak Shiksha Vibhagiya Parikshayen Rajasthan, Bikaner is issuing their Digital awards for the following years, through DigiLocker. These can be pulled by students into their DigiLocker accounts.                 Degree - NA                  Marksheet - NA                  Diploma - NA                  Transcript - NA
  termsOfService: https://apisetu.gov.in/api-policy
  version: 3.0.0
servers:
  - url: 'https://apisetu.gov.in/certificate/v3/rajshaladarpan'
paths:
  
  /tetcr:
    post:
      tags:
        - APIs
      summary: Teachers Eligibility Test Certificate
      description: API to verify Teachers Eligibility Test Certificate.
      security:
        - clientId: []
          apiKey: []
      operationId: tetcr
      requestBody:
        description: Request format
        content:
          application/json:
            schema:
              type: object
              required:
                - txnId
                - format
              properties:
                txnId:
                  type: string
                  format: uuid
                  description: A unique transaction id for this request in UUID format. It is used for tracking the request.
                  example: "f7f1469c-29b0-4325-9dfc-c567200a70f7"
                format:
                  type: string
                  description: The format of the certificate in response.
                  enum:
                    - xml
                    
                    - pdf
                    
                    
                certificateParameters:
                  type: object
                  required:
                    - RROLL
                    - REGNO
                    - YEAR
                    
                    - FullName
                      
                  properties:
                    RROLL:
                      type: string
                      description: Roll No
                      example: "2250001"
                       
                    
                    REGNO:
                      type: string
                      description: Registration No
                      example: "147361"
                       
                    
                    YEAR:
                      type: string
                      description: Year
                      example: ""
                       
                    
                    
                    FullName:
                      type: string
                      description: Full name
                      example: "Sunil Kumar"  
                consentArtifact:
                  $ref: '#/components/schemas/ConsentArtifactSchema'
      responses:
        '200':
          description: The certificate data in response body in PDF, XML or JSON format as requested in format parameter.
          content:
            application/xml:
              schema:  
                $ref: '#/components/schemas/AcademicCertificateSchema'  
            
            
            application/pdf:
              example: Response body contains contents of the certificate in PDF format.
            
            
            
        '400':
          $ref: '#/components/responses/400Error'
        '401':
          $ref: '#/components/responses/401Error'
        '404':
          $ref: '#/components/responses/404Error'
        '500':
          $ref: '#/components/responses/500Error'
        '502':
          $ref: '#/components/responses/502Error'
        '503':
          $ref: '#/components/responses/503Error'
        '504':
          $ref: '#/components/responses/504Error'
  
  /tetms:
    post:
      tags:
        - APIs
      summary: Teachers Eligibility Test Mark Sheet
      description: API to verify Teachers Eligibility Test Mark Sheet.
      security:
        - clientId: []
          apiKey: []
      operationId: tetms
      requestBody:
        description: Request format
        content:
          application/json:
            schema:
              type: object
              required:
                - txnId
                - format
              properties:
                txnId:
                  type: string
                  format: uuid
                  description: A unique transaction id for this request in UUID format. It is used for tracking the request.
                  example: "f7f1469c-29b0-4325-9dfc-c567200a70f7"
                format:
                  type: string
                  description: The format of the certificate in response.
                  enum:
                    - xml
                    
                    - pdf
                    
                    
                certificateParameters:
                  type: object
                  required:
                    - RROLL
                    - REGNO
                    - CERT_NO
                    - YEAR
                    
                    - FullName
                      
                  properties:
                    RROLL:
                      type: string
                      description: Roll No
                      example: "8135907"
                       
                    
                    REGNO:
                      type: string
                      description: Registration No
                      example: "1373"
                       
                    
                    CERT_NO:
                      type: string
                      description: Certificate No
                      example: "23/S/2400325"
                       
                    
                    YEAR:
                      type: string
                      description: Year
                      example: ""
                       
                    
                    
                    FullName:
                      type: string
                      description: Full name
                      example: "Sunil Kumar"  
                consentArtifact:
                  $ref: '#/components/schemas/ConsentArtifactSchema'
      responses:
        '200':
          description: The certificate data in response body in PDF, XML or JSON format as requested in format parameter.
          content:
            application/xml:
              schema:  
                $ref: '#/components/schemas/AcademicCertificateSchema'  
            
            
            application/pdf:
              example: Response body contains contents of the certificate in PDF format.
            
            
            
        '400':
          $ref: '#/components/responses/400Error'
        '401':
          $ref: '#/components/responses/401Error'
        '404':
          $ref: '#/components/responses/404Error'
        '500':
          $ref: '#/components/responses/500Error'
        '502':
          $ref: '#/components/responses/502Error'
        '503':
          $ref: '#/components/responses/503Error'
        '504':
          $ref: '#/components/responses/504Error'
  
components:
  schemas:
    ConsentArtifactSchema:
      $ref: './common/ConsentArtifactSchema.yaml#/ConsentArtifactSchema'
    AcademicCertificateSchema:
      $ref: './common/AcademicCertificateSchema.yaml#/AcademicCertificateSchema'
          
  responses:
    400Error:
      $ref: './common/ErrorResponse.yaml#/400Error'
    401Error:
      $ref: './common/ErrorResponse.yaml#/401Error'
    404Error:
      $ref: './common/ErrorResponse.yaml#/404Error'
    500Error:
      $ref: './common/ErrorResponse.yaml#/500Error'
    502Error:
      $ref: './common/ErrorResponse.yaml#/502Error'
    503Error:
      $ref: './common/ErrorResponse.yaml#/503Error'
    504Error:
      $ref: './common/ErrorResponse.yaml#/504Error'
  securitySchemes:
    clientId:
      type: apiKey
      in: header
      name: X-APISETU-CLIENTID
    apiKey:
      type: apiKey
      in: header
      name: X-APISETU-APIKEY