openapi: 3.0.3
info:  
  title: Securities and Exchange Board of India, Maharashtra
  description:  >- 
                The Securities and Exchange Board of India was constituted as a non-statutory body on April 12, 1988 through a resolution of the Government of India.The Securities and Exchange Board of India was established as a statutory body in the year 1992 and the provisions of the Securities and Exchange Board of India Act, 1992 (15 of 1992) came into force on January 30, 1992.
  termsOfService: https://apisetu.gov.in/api-policy
  version: 3.0.0
servers:
  - url: 'https://apisetu.gov.in/certificate/v3/sebi'
paths:
  
  /ecert:
    post:
      tags:
        - APIs
      summary: Empanelment Certificate
      description: API to verify Empanelment Certificate.
      security:
        - clientId: []
          apiKey: []
      operationId: ecert
      requestBody:
        description: Request format
        content:
          application/json:
            schema:
              type: object
              required:
                - txnId
                - format
              properties:
                txnId:
                  type: string
                  format: uuid
                  description: A unique transaction id for this request in UUID format. It is used for tracking the request.
                  example: "f7f1469c-29b0-4325-9dfc-c567200a70f7"
                format:
                  type: string
                  description: The format of the certificate in response.
                  enum:
                    - xml
                    
                    - pdf
                    
                    
                certificateParameters:
                  type: object
                  required:
                    - EmpanelmentNumber
                    
                    - FullName
                    
                    - DOB
                      
                  properties:
                    EmpanelmentNumber:
                      type: string
                      description: Empanelment Number
                      example: "SIHMH323"
                       
                    
                    
                    FullName:
                      type: string
                      description: Full name
                      example: "Sunil Kumar"
                    DOB:
                      type: string
                      description: Date of birth in DD-MM-YYYY format
                      example: "31-12-1980"  
                consentArtifact:
                  $ref: '#/components/schemas/ConsentArtifactSchema'
      responses:
        '200':
          description: The certificate data in response body in PDF, XML or JSON format as requested in format parameter.
          content:
            application/xml:
              schema:  
                $ref: '#/components/schemas/AcademicCertificateSchema'  
            
            
            application/pdf:
              example: Response body contains contents of the certificate in PDF format.
            
            
            
        '400':
          $ref: '#/components/responses/400Error'
        '401':
          $ref: '#/components/responses/401Error'
        '404':
          $ref: '#/components/responses/404Error'
        '500':
          $ref: '#/components/responses/500Error'
        '502':
          $ref: '#/components/responses/502Error'
        '503':
          $ref: '#/components/responses/503Error'
        '504':
          $ref: '#/components/responses/504Error'
  
components:
  schemas:
    ConsentArtifactSchema:
      $ref: './common/ConsentArtifactSchema.yaml#/ConsentArtifactSchema'
    AcademicCertificateSchema:
      $ref: './common/AcademicCertificateSchema.yaml#/AcademicCertificateSchema'
          
  responses:
    400Error:
      $ref: './common/ErrorResponse.yaml#/400Error'
    401Error:
      $ref: './common/ErrorResponse.yaml#/401Error'
    404Error:
      $ref: './common/ErrorResponse.yaml#/404Error'
    500Error:
      $ref: './common/ErrorResponse.yaml#/500Error'
    502Error:
      $ref: './common/ErrorResponse.yaml#/502Error'
    503Error:
      $ref: './common/ErrorResponse.yaml#/503Error'
    504Error:
      $ref: './common/ErrorResponse.yaml#/504Error'
  securitySchemes:
    clientId:
      type: apiKey
      in: header
      name: X-APISETU-CLIENTID
    apiKey:
      type: apiKey
      in: header
      name: X-APISETU-APIKEY