openapi: 3.0.3
info:  
  title: TAMIL NADU SKILL DEVELOPMENT CORPORATION, Tamil Nadu
  description:  >- 
                Tamil Nadu Skill Development Corporation (TNSDC) was established by Government of Tamil Nadu as a not-for-profit public limited Company incorporated under Section 8 of the Companies Act, 2013 with an objective to provide demand based and industry relevant skills to the youth to enhance their employability and transform the State into skill hub of the country. Since TNSDC has issued an assessment certificates in online to the trainees who have successfully completed we may integrate TNSDC portal with Digi locker system, TNSDC trainees can able to access their certificate
  termsOfService: https://apisetu.gov.in/api-policy
  version: 3.0.0
servers:
  - url: 'https://apisetu.gov.in/certificate/v3/tnskill'
paths:
  
  /skcer:
    post:
      tags:
        - APIs
      summary: Skill Certificate
      description: API to verify Skill Certificate.
      security:
        - clientId: []
          apiKey: []
      operationId: skcer
      requestBody:
        description: Request format
        content:
          application/json:
            schema:
              type: object
              required:
                - txnId
                - format
              properties:
                txnId:
                  type: string
                  format: uuid
                  description: A unique transaction id for this request in UUID format. It is used for tracking the request.
                  example: "f7f1469c-29b0-4325-9dfc-c567200a70f7"
                format:
                  type: string
                  description: The format of the certificate in response.
                  enum:
                    - pdf
                    
                    
                certificateParameters:
                  type: object
                  required:
                    - CandidateEnrollmentID
                      
                  properties:
                    CandidateEnrollmentID:
                      type: string
                      description: CandidateEnrollmentID
                      example: "AR2020F-C00072D"
                       
                    
                      
                consentArtifact:
                  $ref: '#/components/schemas/ConsentArtifactSchema'
      responses:
        '200':
          description: The certificate data in response body in PDF, XML or JSON format as requested in format parameter.
          content:
            application/pdf:
              example: Response body contains contents of the certificate in PDF format.
            
            
            
        '400':
          $ref: '#/components/responses/400Error'
        '401':
          $ref: '#/components/responses/401Error'
        '404':
          $ref: '#/components/responses/404Error'
        '500':
          $ref: '#/components/responses/500Error'
        '502':
          $ref: '#/components/responses/502Error'
        '503':
          $ref: '#/components/responses/503Error'
        '504':
          $ref: '#/components/responses/504Error'
  
  /skmst:
    post:
      tags:
        - APIs
      summary: Skill Marksheet/ Score Card
      description: API to verify Skill Marksheet/ Score Card.
      security:
        - clientId: []
          apiKey: []
      operationId: skmst
      requestBody:
        description: Request format
        content:
          application/json:
            schema:
              type: object
              required:
                - txnId
                - format
              properties:
                txnId:
                  type: string
                  format: uuid
                  description: A unique transaction id for this request in UUID format. It is used for tracking the request.
                  example: "f7f1469c-29b0-4325-9dfc-c567200a70f7"
                format:
                  type: string
                  description: The format of the certificate in response.
                  enum:
                    - pdf
                    
                    
                certificateParameters:
                  type: object
                  required:
                    - CandidateEnrollmentID
                      
                  properties:
                    CandidateEnrollmentID:
                      type: string
                      description: CandidateEnrollmentID
                      example: "AR2020F-C00072D"
                       
                    
                      
                consentArtifact:
                  $ref: '#/components/schemas/ConsentArtifactSchema'
      responses:
        '200':
          description: The certificate data in response body in PDF, XML or JSON format as requested in format parameter.
          content:
            application/pdf:
              example: Response body contains contents of the certificate in PDF format.
            
            
            
        '400':
          $ref: '#/components/responses/400Error'
        '401':
          $ref: '#/components/responses/401Error'
        '404':
          $ref: '#/components/responses/404Error'
        '500':
          $ref: '#/components/responses/500Error'
        '502':
          $ref: '#/components/responses/502Error'
        '503':
          $ref: '#/components/responses/503Error'
        '504':
          $ref: '#/components/responses/504Error'
  
components:
  schemas:
    ConsentArtifactSchema:
      $ref: './common/ConsentArtifactSchema.yaml#/ConsentArtifactSchema'
    AcademicCertificateSchema:
      $ref: './common/AcademicCertificateSchema.yaml#/AcademicCertificateSchema'
          
  responses:
    400Error:
      $ref: './common/ErrorResponse.yaml#/400Error'
    401Error:
      $ref: './common/ErrorResponse.yaml#/401Error'
    404Error:
      $ref: './common/ErrorResponse.yaml#/404Error'
    500Error:
      $ref: './common/ErrorResponse.yaml#/500Error'
    502Error:
      $ref: './common/ErrorResponse.yaml#/502Error'
    503Error:
      $ref: './common/ErrorResponse.yaml#/503Error'
    504Error:
      $ref: './common/ErrorResponse.yaml#/504Error'
  securitySchemes:
    clientId:
      type: apiKey
      in: header
      name: X-APISETU-CLIENTID
    apiKey:
      type: apiKey
      in: header
      name: X-APISETU-APIKEY